export default [
  {
    id: `lightside_hard_1a`,
    table: "Light Side",
    difficulty: "Hard",
    map: 1,
    mission: "A",
    energy: 12,
    characters: ["REY"],
    gear: [
      {
        id: "002",
        dropRate: 1,
      },
      {
        id: "004",
        dropRate: 1,
      },
      {
        id: "005",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_1b`,
    table: "Light Side",
    difficulty: "Hard",
    map: 1,
    mission: "B",
    energy: 12,
    characters: ["AHSOKATANO"],
    gear: [
      {
        id: "002",
        dropRate: 1,
      },
      {
        id: "007",
        dropRate: 1,
      },
      {
        id: "011",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_1c`,
    table: "Light Side",
    difficulty: "Hard",
    map: 1,
    mission: "C",
    energy: 12,
    characters: ["DARKTROOPER"],
    gear: [
      {
        id: "012",
        dropRate: 1,
      },
      {
        id: "009",
        dropRate: 1,
      },
      {
        id: "001",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_1d`,
    table: "Light Side",
    difficulty: "Hard",
    map: 1,
    mission: "D",
    energy: 12,
    characters: ["KYLORENUNMASKED"],
    gear: [
      {
        id: "002",
        dropRate: 1,
      },
      {
        id: "003",
        dropRate: 1,
      },
      {
        id: "008",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_2a`,
    table: "Light Side",
    difficulty: "Hard",
    map: 2,
    mission: "A",
    energy: 12,
    characters: ["EWOKSCOUT", "EWOKELDER"],
    gear: [
      {
        id: "006",
        dropRate: 1,
      },
      {
        id: "014Prototype",
        dropRate: 1,
      },
      {
        id: "010",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_2b`,
    table: "Light Side",
    difficulty: "Hard",
    map: 2,
    mission: "B",
    energy: 12,
    characters: ["FIRSTORDERTROOPER", "FOSITHTROOPER"],
    gear: [
      {
        id: "019",
        dropRate: 1,
      },
      {
        id: "002",
        dropRate: 1,
      },
      {
        id: "017Prototype",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_2c`,
    table: "Light Side",
    difficulty: "Hard",
    map: 2,
    mission: "C",
    characters: ["BT1"],
    gear: [
      {
        id: "007",
        dropRate: 1,
      },
      {
        id: "008",
        dropRate: 1,
      },
      {
        id: "001",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_2d`,
    table: "Light Side",
    difficulty: "Hard",
    map: 2,
    mission: "D",
    characters: ["MOFFGIDEONS1"],
    gear: [
      {
        id: "033",
        dropRate: 1,
      },
      {
        id: "004",
        dropRate: 1,
      },
      {
        id: "021",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_2e`,
    table: "Light Side",
    difficulty: "Hard",
    map: 2,
    mission: "E",
    characters: ["MACEWINDU"],
    gear: [
      {
        id: "020",
        dropRate: 1,
      },
      {
        id: "009",
        dropRate: 1,
      },
      {
        id: "001",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_2f`,
    table: "Light Side",
    difficulty: "Hard",
    map: 2,
    mission: "F",
    characters: ["HERASYNDULLAS3", "GHOST"],
    gear: [
      {
        id: "035",
        dropRate: 1,
      },
      {
        id: "003",
        dropRate: 1,
      },
      {
        id: "015Prototype",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_3a`,
    table: "Light Side",
    difficulty: "Hard",
    map: 3,
    mission: "A",
    characters: ["CEREJUNDA"],
    gear: [
      {
        id: "050Salvage",
        dropRate: 1,
      },
      {
        id: "016",
        dropRate: 1,
      },
      {
        id: "001",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_3b`,
    table: "Light Side",
    difficulty: "Hard",
    map: 3,
    mission: "B",
    characters: ["UNDERCOVERLANDO"],
    gear: [
      {
        id: "034",
        dropRate: 1,
      },
      {
        id: "030",
        dropRate: 1,
      },
      {
        id: "006",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_3c`,
    table: "Light Side",
    difficulty: "Hard",
    map: 3,
    mission: "C",
    characters: ["STORMTROOPER"],
    gear: [
      {
        id: "025",
        dropRate: 1,
      },
      {
        id: "004",
        dropRate: 1,
      },
      {
        id: "013",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_3d`,
    table: "Light Side",
    difficulty: "Hard",
    map: 3,
    mission: "D",
    characters: ["NINTHSISTER"],
    gear: [
      {
        id: "036",
        dropRate: 1,
      },
      {
        id: "031Prototype",
        dropRate: 1,
      },
      {
        id: "013",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_3e`,
    table: "Light Side",
    difficulty: "Hard",
    map: 3,
    mission: "E",
    characters: ["GREEFKARGA", "IG11"],
    gear: [
      {
        id: "057Salvage",
        dropRate: 1,
      },
      {
        id: "015",
        dropRate: 1,
      },
      {
        id: "009",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_3f`,
    table: "Light Side",
    difficulty: "Hard",
    map: 3,
    mission: "F",
    characters: ["DATHCHA"],
    gear: [
      {
        id: "028Prototype",
        dropRate: 1,
      },
      {
        id: "012",
        dropRate: 1,
      },
      {
        id: "005",
        dropRate: 1,
      },
      {
        id: "010",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_4a`,
    table: "Light Side",
    difficulty: "Hard",
    map: 4,
    mission: "A",
    characters: ["PAZVIZSLA"],
    gear: [
      {
        id: "078Prototype",
        dropRate: 1,
      },
      {
        id: "069Prototype",
        dropRate: 1,
      },
      {
        id: "015Prototype",
        dropRate: 1,
      },
      {
        id: "010",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_4b`,
    table: "Light Side",
    difficulty: "Hard",
    map: 4,
    mission: "B",
    characters: ["SAWGERRERA"],
    gear: [
      {
        id: "055Prototype",
        dropRate: 1,
      },
      {
        id: "052Salvage",
        dropRate: 1,
      },
      {
        id: "007",
        dropRate: 1,
      },
      {
        id: "017Prototype",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_4c`,
    table: "Light Side",
    difficulty: "Hard",
    map: 4,
    mission: "C",
    characters: ["VEERS"],
    gear: [
      {
        id: "055PrototypeSalvage",
        dropRate: 1,
      },
      {
        id: "040Prototype",
        dropRate: 1,
      },
      {
        id: "013",
        dropRate: 1,
      },
      {
        id: "007",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_4d`,
    table: "Light Side",
    difficulty: "Hard",
    map: 4,
    mission: "D",
    characters: ["IDENVERSIOEMPIRE", "VULTUREDROID"],
    gear: [
      {
        id: "051Salvage",
        dropRate: 1,
      },
      {
        id: "044Prototype",
        dropRate: 1,
      },
      {
        id: "009",
        dropRate: 1,
      },
      {
        id: "021Prototype",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_4e`,
    table: "Light Side",
    difficulty: "Hard",
    map: 4,
    mission: "E",
    characters: ["POGGLETHELESSER"],
    gear: [
      {
        id: "062Salvage",
        dropRate: 1,
      },
      {
        id: "049Prototype",
        dropRate: 1,
      },
      {
        id: "003",
        dropRate: 1,
      },
      {
        id: "008",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_4f`,
    table: "Light Side",
    difficulty: "Hard",
    map: 4,
    mission: "F",
    characters: ["ROSETICO", "RESISTANCETROOPER"],
    gear: [
      {
        id: "053Salvage",
        dropRate: 1,
      },
      {
        id: "035",
        dropRate: 1,
      },
      {
        id: "036",
        dropRate: 1,
      },
      {
        id: "001",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_5a`,
    table: "Light Side",
    difficulty: "Hard",
    map: 5,
    mission: "A",
    characters: ["URORRURRR"],
    gear: [
      {
        id: "051Salvage",
        dropRate: 1,
      },
      {
        id: "062Salvage",
        dropRate: 1,
      },
      {
        id: "071PrototypeSalvage",
        dropRate: 1,
      },
      {
        id: "027",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_5b`,
    table: "Light Side",
    difficulty: "Hard",
    map: 5,
    mission: "B",
    characters: ["BADBATCHHUNTER"],
    gear: [
      {
        id: "086PrototypeSalvage",
        dropRate: 1,
      },
      { id: "028Prototype", dropRate: 1 },
      {
        id: "061Prototype",
        dropRate: 1,
      },
      {
        id: "095Salvage",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_5c`,
    table: "Light Side",
    difficulty: "Hard",
    map: 5,
    mission: "C",
    characters: ["PRINCESSKNEESAA"],
    gear: [
      {
        id: "091Salvage",
        dropRate: 1,
      },
      {
        id: "071PrototypeSalvage",
        dropRate: 1,
      },
      {
        id: "033",
        dropRate: 1,
      },
      {
        id: "030",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_5d`,
    table: "Light Side",
    difficulty: "Hard",
    map: 5,
    mission: "D",
    characters: ["ZAALBAR", "MISSIONVAO"],
    gear: [
      {
        id: "097PrototypeSalvage",
        dropRate: 1,
      },
      {
        id: "054Salvage",
        dropRate: 1,
      },
      {
        id: "027",
        dropRate: 1,
      },
      {
        id: "025",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_5e`,
    table: "Light Side",
    difficulty: "Hard",
    map: 5,
    mission: "E",
    characters: ["MONMOTHMA"],
    gear: [
      {
        id: "084PrototypeSalvage",
        dropRate: 1,
      },
      {
        id: "085PrototypeSalvage",
        dropRate: 1,
      },
      {
        id: "034",
        dropRate: 1,
      },
      {
        id: "031Prototype",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_5f`,
    table: "Light Side",
    difficulty: "Hard",
    map: 5,
    mission: "F",
    characters: ["BADBATCHTECH"],
    gear: [
      {
        id: "101Salvage",
        dropRate: 1,
      },
      {
        id: "052Salvage",
        dropRate: 1,
      },
      {
        id: "066",
        dropRate: 1,
      },
      {
        id: "004",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_6a`,
    table: "Light Side",
    difficulty: "Hard",
    map: 6,
    mission: "A",
    characters: ["BOOMADIER"],
    gear: [
      {
        id: "100PrototypeSalvage",
        dropRate: 1,
      },
      {
        id: "102Salvage",
        dropRate: 1,
      },
      {
        id: "076Salvage",
        dropRate: 1,
      },
      {
        id: "093PrototypeSalvage",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_6b`,
    table: "Light Side",
    difficulty: "Hard",
    map: 6,
    mission: "B",
    characters: ["ADMIRALPIETT", "EPIXPOE"],
    gear: [
      {
        id: "090PrototypeSalvage",
        dropRate: 1,
      },
      {
        id: "103PrototypeSalvage",
        dropRate: 1,
      },
      {
        id: "057Salvage",
        dropRate: 1,
      },
      {
        id: "071PrototypeSalvage",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_6c`,
    table: "Light Side",
    difficulty: "Hard",
    map: 6,
    mission: "C",
    characters: ["FENNECSHAND", "SITHBOMBER"],
    gear: [
      {
        id: "104PrototypeSalvage",
        dropRate: 1,
      },
      {
        id: "050Salvage",
        dropRate: 1,
      },
      {
        id: "078PrototypeSalvage",
        dropRate: 1,
      },
      {
        id: "095Salvage",
        dropRate: 1,
      },
    ],
  },
  {
    id: `lightside_hard_6d`,
    table: "Light Side",
    difficulty: "Hard",
    map: 6,
    mission: "D",
    characters: ["MARAJADE"],
    gear: [],
  },
  {
    id: `lightside_hard_6e`,
    table: "Light Side",
    difficulty: "Hard",
    map: 6,
    mission: "E",
    characters: ["EIGHTHBROTHER", "IG2000"],
    gear: [],
  },
  {
    id: `lightside_hard_7a`,
    table: "Light Side",
    difficulty: "Hard",
    map: 7,
    mission: "A",
    characters: ["C3POCHEWBACCA"],
    gear: [],
  },
  {
    id: `lightside_hard_7b`,
    table: "Light Side",
    difficulty: "Hard",
    map: 7,
    mission: "B",
    characters: ["POE"],
    gear: [],
  },
  {
    id: `lightside_hard_7c`,
    table: "Light Side",
    difficulty: "Hard",
    map: 7,
    mission: "C",
    characters: ["BADBATCHWRECKER", "YWINGCLONEWARS"],
    gear: [],
  },
  {
    id: `lightside_hard_7d`,
    table: "Light Side",
    difficulty: "Hard",
    map: 7,
    mission: "D",
    characters: ["BADBATCHECHO", "LUKESKYWALKER"],
    gear: [],
  },
  {
    id: `lightside_hard_8a`,
    table: "Light Side",
    difficulty: "Hard",
    map: 8,
    mission: "A",
    characters: ["MOTHERTALZIN", "MARROK"],
    gear: [],
  },
  {
    id: `lightside_hard_8b`,
    table: "Light Side",
    difficulty: "Hard",
    map: 8,
    mission: "B",
    characters: ["DROIDEKA", "XANADUBLOOD"],
    gear: [],
  },
  {
    id: `lightside_hard_8c`,
    table: "Light Side",
    difficulty: "Hard",
    map: 8,
    mission: "C",
    characters: ["EPIXFINN", "CAPTAINENOCH"],
    gear: [],
  },
  {
    id: `lightside_hard_8d`,
    table: "Light Side",
    difficulty: "Hard",
    map: 8,
    mission: "D",
    characters: ["JANGOFETT", "HOUNDSTOOTH"],
    gear: [],
  },
  {
    id: `lightside_hard_9a`,
    table: "Light Side",
    difficulty: "Hard",
    map: 9,
    mission: "A",
    characters: ["DARTHSION", "COMMANDSHUTTLE"],
    gear: [],
  },
  {
    id: `lightside_hard_9b`,
    table: "Light Side",
    difficulty: "Hard",
    map: 9,
    mission: "A",
    characters: ["SHORETROOPER", "TIEREAPER"],
    gear: [],
  },
  {
    id: `lightside_hard_9c`,
    table: "Light Side",
    difficulty: "Hard",
    map: 9,
    mission: "C",
    characters: ["ARMORER", "BAZEMALBUS"],
    gear: [],
  },
  {
    id: `lightside_hard_9d`,
    table: "Light Side",
    difficulty: "Hard",
    map: 9,
    mission: "D",
    characters: ["DIRECTORKRENNIC", "GEONOSIANSTARFIGHTER2"],
    gear: [],
  },
  {
    id: `darkside_hard_1a`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 1,
    mission: "A",
    characters: ["SABINEWRENS3"],
    gear: [],
  },
  {
    id: `darkside_hard_1b`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 1,
    mission: "B",
    characters: ["ANAKINKNIGHT"],
    gear: [],
  },
  {
    id: `darkside_hard_1c`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 1,
    mission: "C",
    characters: ["ZORIIBLISS_V2", "PRINCESSLEIA"],
    gear: [],
  },
  {
    id: `darkside_hard_1d`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 1,
    mission: "D",
    characters: ["JEDIKNIGHTCONSULAR", "CHOPPERS3"],
    gear: [],
  },
  {
    id: `darkside_hard_2a`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 2,
    mission: "A",
    characters: ["TRIPLEZERO"],
    gear: [],
  },
  {
    id: `darkside_hard_2b`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 2,
    mission: "B",
    characters: ["BOBAFETT"],
    gear: [],
  },
  {
    id: `darkside_hard_2c`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 2,
    mission: "C",
    characters: ["BOUSHH"],
    gear: [],
  },
  {
    id: `darkside_hard_2d`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 2,
    mission: "D",
    energy: 12,
    characters: ["CT5555", "UMBARANSTARFIGHTER"],
    gear: [],
  },
  {
    id: `darkside_hard_2e`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 2,
    mission: "E",
    energy: 12,
    characters: ["KELLERANBEQ"],
    gear: [],
  },
  {
    id: `darkside_hard_2f`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 2,
    mission: "F",
    energy: 12,
    characters: ["IG86SENTINELDROID"],
    gear: [],
  },
  {
    id: `darkside_hard_3a`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 3,
    mission: "A",
    energy: 12,
    characters: ["RANGETROOPER"],
    gear: [],
  },
  {
    id: `darkside_hard_3b`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 3,
    mission: "B",
    energy: 12,
    characters: ["HOTHREBELSCOUT"],
    gear: [],
  },
  {
    id: `darkside_hard_3c`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 3,
    mission: "C",
    energy: 12,
    characters: ["THEMANDALORIAN"],
    gear: [],
  },
  {
    id: `darkside_hard_3d`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 3,
    mission: "D",
    energy: 12,
    characters: ["TEEBO"],
    gear: [],
  },
  {
    id: `darkside_hard_3e`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 3,
    mission: "E",
    energy: 12,
    characters: ["50RT"],
    gear: [],
  },
  {
    id: `darkside_hard_3f`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 3,
    mission: "F",
    energy: 12,
    characters: ["CAPTAINREX"],
    gear: [],
  },
  {
    id: `darkside_hard_4a`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 4,
    mission: "A",
    energy: 12,
    characters: ["ADMIRALRADDUS"],
    gear: [],
  },
  {
    id: `darkside_hard_4b`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 4,
    mission: "B",
    energy: 12,
    characters: ["DAKA"],
    gear: [],
  },
  {
    id: `darkside_hard_4c`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 4,
    mission: "C",
    energy: 12,
    characters: ["SECONDSISTER"],
    gear: [],
  },
  {
    id: `darkside_hard_4d`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 4,
    mission: "D",
    energy: 12,
    characters: ["YOUNGCHEWBACCA", "TARFFUL"],
    gear: [],
  },
  {
    id: `darkside_hard_4e`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 4,
    mission: "E",
    energy: 12,
    characters: ["SEVENTHSISTER"],
    gear: [],
  },
  {
    id: `darkside_hard_4f`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 4,
    mission: "F",
    energy: 12,
    characters: ["JAWA"],
    gear: [
      {
        id: "006",
        dropRate: 1,
      },
    ],
  },
  {
    id: `darkside_hard_5a`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 5,
    mission: "A",
    energy: 16,
    characters: ["KUIIL", "TIEBOMBERIMPERIAL"],
    gear: [],
  },
  {
    id: `darkside_hard_5b`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 5,
    mission: "B",
    energy: 16,
    characters: ["BASTILASHAN"],
    gear: [],
  },
  {
    id: `darkside_hard_5c`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 5,
    mission: "C",
    energy: 16,
    characters: ["BARRISSOFFEE", "IMAGUNDI"],
    gear: [],
  },
  {
    id: `darkside_hard_5d`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 5,
    mission: "D",
    energy: 16,
    characters: ["REY", "MILLENNIUMFALCONEP7"],
    gear: [],
  },
  {
    id: `darkside_hard_5e`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 5,
    mission: "E",
    energy: 16,
    characters: ["CARADUNE"],
    gear: [],
  },
  {
    id: `darkside_hard_5f`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 5,
    mission: "F",
    energy: 16,
    characters: ["ROYALGUARD"],
    gear: [],
  },
  {
    id: `darkside_hard_6a`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 6,
    mission: "A",
    energy: 16,
    characters: ["GENERALHUX", "HOTHREBELSCOUT"],
    gear: [],
  },
  {
    id: `darkside_hard_6b`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 6,
    mission: "B",
    energy: 16,
    characters: ["FIRSTORDERTIEPILOT"],
    gear: [],
  },
  {
    id: `darkside_hard_6c`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 6,
    mission: "C",
    energy: 16,
    characters: ["TUSKENCHIEFTAIN", "TUSKENRAIDER"],
    gear: [],
  },
  {
    id: `darkside_hard_6d`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 6,
    mission: "D",
    energy: 16,
    characters: ["BOKATAN", "JOLEEBINDO"],
    gear: [],
  },
  {
    id: `darkside_hard_6e`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 6,
    mission: "E",
    energy: 16,
    characters: ["MAGNAGUARD"],
    gear: [],
  },
  {
    id: `darkside_hard_7a`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 7,
    mission: "A",
    energy: 20,
    characters: ["BASTILASHANDARK"],
    gear: [],
  },
  {
    id: `darkside_hard_7b`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 7,
    mission: "B",
    energy: 20,
    characters: ["VISASMARR"],
    gear: [],
  },
  {
    id: `darkside_hard_7c`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 7,
    mission: "C",
    energy: 20,
    characters: ["AMILYNHOLDO"],
    gear: [],
  },
  {
    id: `darkside_hard_7d`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 7,
    mission: "D",
    energy: 20,
    characters: ["EMPERORSSHUTTLE"],
    gear: [],
  },
  {
    id: `darkside_hard_8a`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 8,
    mission: "A",
    energy: 20,
    characters: ["WICKET", "DEATHTROOPERPERIDEA"],
    gear: [],
  },
  {
    id: `darkside_hard_8b`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 8,
    mission: "B",
    energy: 20,
    characters: ["HYENABOMBER", "JEDISTARFIGHTERCONSULAR"],
    gear: [],
  },
  {
    id: `darkside_hard_8c`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 8,
    mission: "C",
    energy: 20,
    characters: ["NIGHTTROOPER"],
    gear: [],
  },
  {
    id: `darkside_hard_8d`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 8,
    mission: "D",
    energy: 20,
    characters: ["BOSSNASS"],
    gear: [],
  },
  {
    id: `darkside_hard_9a`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 9,
    mission: "A",
    energy: 20,
    characters: ["DARTHNIHILUS"],
    gear: [],
  },
  {
    id: `darkside_hard_9b`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 9,
    mission: "B",
    energy: 20,
    characters: ["BOSSK"],
    gear: [],
  },
  {
    id: `darkside_hard_9c`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 9,
    mission: "C",
    energy: 20,
    characters: ["SHINHATI"],
    gear: [],
  },
  {
    id: `darkside_hard_9d`,
    table: "Dark Side",
    difficulty: "Hard",
    map: 9,
    mission: "D",
    energy: 20,
    characters: ["PHANTOM2"],
    gear: [],
  },
  {
    id: `fleet_hard_1a`,
    table: "Fleet",
    difficulty: "Hard",
    map: 1,
    mission: "A",
    energy: 16,
    characters: ["ARC170CLONESERGEANT"],
    gear: [],
  },
  {
    id: `fleet_hard_1b`,
    table: "Fleet",
    difficulty: "Hard",
    map: 1,
    mission: "B",
    energy: 16,
    characters: ["JEDISTARFIGHTERANAKIN"],
    gear: [],
  },
  {
    id: `fleet_hard_1c`,
    table: "Fleet",
    difficulty: "Hard",
    map: 1,
    mission: "C",
    energy: 16,
    characters: ["MERRIN"],
    gear: [],
  },
  {
    id: `fleet_hard_1d`,
    table: "Fleet",
    difficulty: "Hard",
    map: 1,
    mission: "D",
    energy: 16,
    characters: ["YOUNGLANDO", "MILLENNIUMFALCONPRISTINE"],
    gear: [],
  },
  {
    id: `fleet_hard_1d`,
    table: "Fleet",
    difficulty: "Hard",
    map: 1,
    mission: "D",
    energy: 16,
    characters: ["XWINGRESISTANCE"],
    gear: [],
  },
  {
    id: `fleet_hard_2a`,
    table: "Fleet",
    difficulty: "Hard",
    map: 2,
    mission: "A",
    energy: 20,
    characters: ["GEONOSIANSTARFIGHTER1"],
    gear: [],
  },
  {
    id: `fleet_hard_2b`,
    table: "Fleet",
    difficulty: "Hard",
    map: 2,
    mission: "B",
    energy: 20,
    characters: ["SLAVE1"],
    gear: [],
  },
  {
    id: `fleet_hard_2c`,
    table: "Fleet",
    difficulty: "Hard",
    map: 2,
    mission: "C",
    energy: 20,
    characters: ["IG12"],
    gear: [],
  },
  {
    id: `fleet_hard_2d`,
    table: "Fleet",
    difficulty: "Hard",
    map: 2,
    mission: "D",
    energy: 20,
    characters: ["MG100STARFORTRESSSF17"],
    gear: [],
  },
  {
    id: `fleet_hard_2e`,
    table: "Fleet",
    difficulty: "Hard",
    map: 2,
    mission: "E",
    energy: 20,
    characters: ["RAVENSCLAW"],
    gear: [],
  },
  {
    id: `fleet_hard_3a`,
    table: "Fleet",
    difficulty: "Hard",
    map: 3,
    mission: "A",
    energy: 20,
    characters: ["XWINGBLACKONE"],
    gear: [],
  },
  {
    id: `fleet_hard_3b`,
    table: "Fleet",
    difficulty: "Hard",
    map: 3,
    mission: "B",
    energy: 20,
    characters: ["TIEDEFENDER"],
    gear: [],
  },
  {
    id: `fleet_hard_3c`,
    table: "Fleet",
    difficulty: "Hard",
    map: 3,
    mission: "C",
    energy: 20,
    characters: ["OUTRIDER"],
    gear: [],
  },
  {
    id: `fleet_hard_3d`,
    table: "Fleet",
    difficulty: "Hard",
    map: 3,
    mission: "D",
    energy: 20,
    characters: ["SITHINFILTRATOR"],
    gear: [],
  },
  {
    id: `fleet_hard_3e`,
    table: "Fleet",
    difficulty: "Hard",
    map: 3,
    mission: "E",
    energy: 20,
    characters: ["MARAUDER"],
    gear: [],
  },
  {
    id: `fleet_hard_4a`,
    table: "Fleet",
    difficulty: "Hard",
    map: 4,
    mission: "A",
    energy: 20,
    characters: ["GAUNTLETSTARFIGHTER", "IMPERIALSUPERCOMMANDO"],
    gear: [],
  },
  {
    id: `fleet_hard_4b`,
    table: "Fleet",
    difficulty: "Hard",
    map: 4,
    mission: "B",
    energy: 20,
    characters: ["TIEADVANCED"],
    gear: [],
  },
  {
    id: `fleet_hard_4c`,
    table: "Fleet",
    difficulty: "Hard",
    map: 4,
    mission: "C",
    energy: 20,
    characters: ["GREEFKARGA", "YWINGREBEL"],
    gear: [],
  },
  {
    id: `fleet_hard_4d`,
    table: "Fleet",
    difficulty: "Hard",
    map: 4,
    mission: "D",
    energy: 20,
    characters: ["GUNGANPHALANX"],
    gear: [],
  },
  {
    id: `fleet_hard_4e`,
    table: "Fleet",
    difficulty: "Hard",
    map: 4,
    mission: "E",
    energy: 20,
    characters: ["FIRSTORDERTIEECHELON"],
    gear: [],
  },
  {
    id: `fleet_hard_5a`,
    table: "Fleet",
    difficulty: "Hard",
    map: 5,
    mission: "A",
    energy: 20,
    characters: ["SHAAKTI"],
    gear: [],
  },
  {
    id: `fleet_hard_5b`,
    table: "Fleet",
    difficulty: "Hard",
    map: 5,
    mission: "B",
    energy: 20,
    characters: ["B1BATTLEDROIDV2"],
    gear: [],
  },
  {
    id: `fleet_hard_5c`,
    table: "Fleet",
    difficulty: "Hard",
    map: 5,
    mission: "C",
    energy: 20,
    characters: ["SCOUTTROOPER_V3"],
    gear: [],
  },

  {
    id: `fleet_hard_5d`,
    table: "Fleet",
    difficulty: "Hard",
    map: 5,
    mission: "D",
    energy: 20,
    characters: ["ENFYSNEST"],
    gear: [],
  },
  {
    id: `fleet_hard_5e`,
    table: "Fleet",
    difficulty: "Hard",
    map: 5,
    mission: "E",
    energy: 20,
    characters: ["THEMANDALORIAN"],
    gear: [],
  },
  {
    id: `fleet_hard_5f`,
    table: "Fleet",
    difficulty: "Hard",
    map: 5,
    mission: "F",
    energy: 20,
    characters: [],
    gear: [],
  },
  {
    id: `cantina_1a`,
    table: "Cantina",
    difficulty: "",
    map: 1,
    mission: "A",
    energy: 8,
    characters: ["GEONOSIANSOLDIER"],
    gear: [],
  },
  {
    id: `cantina_1b`,
    table: "Cantina",
    difficulty: "",
    map: 1,
    mission: "B",
    energy: 8,
    characters: ["LUKESKYWALKER"],
    gear: [],
  },
  {
    id: `cantina_1c`,
    table: "Cantina",
    difficulty: "",
    map: 1,
    mission: "C",
    energy: 8,
    characters: ["OLDBENKENOBI"],
    gear: [],
  },
  {
    id: `cantina_1d`,
    table: "Cantina",
    difficulty: "",
    map: 1,
    mission: "D",
    energy: 8,
    characters: ["HONDO"],
    gear: [],
  },
  {
    id: `cantina_1e`,
    table: "Cantina",
    difficulty: "",
    map: 1,
    mission: "E",
    energy: 8,
    characters: ["ADMINISTRATORLANDO", "LOBOT"],
    gear: [],
  },
  {
    id: `cantina_1f`,
    table: "Cantina",
    difficulty: "",
    map: 1,
    mission: "F",
    energy: 8,
    characters: ["CALKESTIS"],
    gear: [],
  },
  {
    id: `cantina_1g`,
    table: "Cantina",
    difficulty: "",
    map: 1,
    mission: "G",
    energy: 8,
    characters: ["TALIA", "ZEBS3"],
    gear: [],
  },
  {
    id: `cantina_2a`,
    table: "Cantina",
    difficulty: "",
    map: 2,
    mission: "A",
    energy: 8,
    characters: ["CAPTAINTARPALS", "STORMTROOPERHAN"],
    gear: [],
  },
  {
    id: `cantina_2b`,
    table: "Cantina",
    difficulty: "",
    map: 2,
    mission: "B",
    energy: 8,
    characters: ["EZRABRIDGERS3", "KANANJARRUSS3"],
    gear: [],
  },
  {
    id: `cantina_2c`,
    table: "Cantina",
    difficulty: "",
    map: 2,
    mission: "C",
    energy: 8,
    characters: ["SANASTARROS"],
    gear: [],
  },
  {
    id: `cantina_2d`,
    table: "Cantina",
    difficulty: "",
    map: 2,
    mission: "D",
    energy: 8,
    characters: ["TUSKENHUNTRESS"],
    gear: [],
  },
  {
    id: `cantina_2e`,
    table: "Cantina",
    difficulty: "",
    map: 2,
    mission: "E",
    energy: 8,
    characters: ["GARSAXON"],
    gear: [],
  },
  {
    id: `cantina_2f`,
    table: "Cantina",
    difficulty: "",
    map: 2,
    mission: "F",
    energy: 8,
    characters: ["CLONEWARSCHEWBACCA"],
    gear: [],
  },
  {
    id: `cantina_2g`,
    table: "Cantina",
    difficulty: "",
    map: 2,
    mission: "G",
    energy: 8,
    characters: ["FIRSTORDEREXECUTIONER"],
    gear: [],
  },
  {
    id: `cantina_3a`,
    table: "Cantina",
    difficulty: "",
    map: 3,
    mission: "A",
    energy: 10,
    characters: ["COMEUPPANCE"],
    gear: [],
  },
  {
    id: `cantina_3b`,
    table: "Cantina",
    difficulty: "",
    map: 3,
    mission: "B",
    energy: 10,
    characters: ["QIRA"],
    gear: [],
  },
  {
    id: `cantina_3c`,
    table: "Cantina",
    difficulty: "",
    map: 3,
    mission: "C",
    energy: 10,
    characters: ["MAGNAGUARD"],
    gear: [],
  },
  {
    id: `cantina_3d`,
    table: "Cantina",
    difficulty: "",
    map: 3,
    mission: "D",
    energy: 10,
    characters: ["PAPLOO"],
    gear: [],
  },
  {
    id: `cantina_3e`,
    table: "Cantina",
    difficulty: "",
    map: 3,
    mission: "E",
    energy: 10,
    characters: ["FINN"],
    gear: [],
  },
  {
    id: `cantina_3f`,
    table: "Cantina",
    difficulty: "",
    map: 3,
    mission: "F",
    energy: 10,
    characters: ["KYLORENUNMASKED", "TIESILENCER"],
    gear: [],
  },
  {
    id: `cantina_3g`,
    table: "Cantina",
    difficulty: "",
    map: 3,
    mission: "G",
    energy: 10,
    characters: ["BIGGSDARKLIGHTER"],
    gear: [],
  },
  {
    id: `cantina_4a`,
    table: "Cantina",
    difficulty: "",
    map: 4,
    mission: "A",
    energy: 10,
    characters: ["FIFTHBROTHER"],
    gear: [],
  },
  {
    id: `cantina_4b`,
    table: "Cantina",
    difficulty: "",
    map: 4,
    mission: "B",
    energy: 10,
    characters: ["TIEFIGHTERPILOT", "TIEFIGHTERIMPERIAL"],
    gear: [],
  },
  {
    id: `cantina_4c`,
    table: "Cantina",
    difficulty: "",
    map: 4,
    mission: "C",
    energy: 10,
    characters: ["KYLOREN"],
    gear: [],
  },
  {
    id: `cantina_4d`,
    table: "Cantina",
    difficulty: "",
    map: 4,
    mission: "D",
    energy: 10,
    characters: ["GEONOSIANSPY"],
    gear: [],
  },
  {
    id: `cantina_4e`,
    table: "Cantina",
    difficulty: "",
    map: 4,
    mission: "E",
    energy: 10,
    characters: ["MOFFGIDEONS1"],
    gear: [],
  },
  {
    id: `cantina_4f`,
    table: "Cantina",
    difficulty: "",
    map: 4,
    mission: "F",
    energy: 10,
    characters: ["KITFISTO"],
    gear: [],
  },
  {
    id: `cantina_4g`,
    table: "Cantina",
    difficulty: "",
    map: 4,
    mission: "G",
    energy: 10,
    characters: ["EBONHAWK", "CARTHONASI"],
    gear: [],
  },
  {
    id: `cantina_5a`,
    table: "Cantina",
    difficulty: "",
    map: 5,
    mission: "A",
    energy: 12,
    characters: ["L3_37"],
    gear: [],
  },
  {
    id: `cantina_5b`,
    table: "Cantina",
    difficulty: "",
    map: 5,
    mission: "B",
    energy: 12,
    characters: ["AAYLASECURA"],
    gear: [],
  },
  {
    id: `cantina_5c`,
    table: "Cantina",
    difficulty: "",
    map: 5,
    mission: "C",
    energy: 12,
    characters: ["CANDEROUSORDO"],
    gear: [],
  },
  {
    id: `cantina_5d`,
    table: "Cantina",
    difficulty: "",
    map: 5,
    mission: "D",
    energy: 12,
    characters: ["CHIEFCHIRPA"],
    gear: [],
  },
  {
    id: `cantina_5e`,
    table: "Cantina",
    difficulty: "",
    map: 5,
    mission: "E",
    energy: 12,
    characters: ["SMUGGLERHAN"],
    gear: [],
  },
  {
    id: `cantina_5f`,
    table: "Cantina",
    difficulty: "",
    map: 5,
    mission: "F",
    energy: 12,
    characters: ["SMUGGLERCHEWBACCA"],
    gear: [],
  },
  {
    id: `cantina_5g`,
    table: "Cantina",
    difficulty: "",
    map: 5,
    mission: "G",
    energy: 12,
    characters: ["ARCTROOPER501ST"],
    gear: [],
  },
  {
    id: `cantina_6a`,
    table: "Cantina",
    difficulty: "",
    map: 6,
    mission: "A",
    energy: 12,
    characters: ["KYLEKATARN"],
    gear: [],
  },
  {
    id: `cantina_6b`,
    table: "Cantina",
    difficulty: "",
    map: 6,
    mission: "B",
    energy: 12,
    characters: ["T3_M4"],
    gear: [],
  },
  {
    id: `cantina_6c`,
    table: "Cantina",
    difficulty: "",
    map: 6,
    mission: "C",
    energy: 12,
    characters: ["SITHASSASSIN", "SITHFIGHTER"],
    gear: [],
  },
  {
    id: `cantina_6d`,
    table: "Cantina",
    difficulty: "",
    map: 6,
    mission: "D",
    energy: 12,
    characters: ["B2SUPERBATTLEDROID"],
    gear: [],
  },
  {
    id: `cantina_6e`,
    table: "Cantina",
    difficulty: "",
    map: 6,
    mission: "E",
    energy: 12,
    characters: ["SITHMARAUDER"],
    gear: [],
  },
  {
    id: `cantina_6f`,
    table: "Cantina",
    difficulty: "",
    map: 6,
    mission: "F",
    energy: 12,
    characters: ["CAPTAINDROGAN"],
    gear: [],
  },
  {
    id: `cantina_6g`,
    table: "Cantina",
    difficulty: "",
    map: 6,
    mission: "G",
    energy: 12,
    characters: ["COUNTDOOKU"],
    gear: [],
  },
  {
    id: `cantina_7a`,
    table: "Cantina",
    difficulty: "",
    map: 7,
    mission: "A",
    energy: 16,
    characters: ["KRRSANTAN"],
    gear: [],
  },
  {
    id: `cantina_7b`,
    table: "Cantina",
    difficulty: "",
    map: 7,
    mission: "B",
    energy: 16,
    characters: ["MORGANELSBETH"],
    gear: [],
  },
  {
    id: `cantina_7c`,
    table: "Cantina",
    difficulty: "",
    map: 7,
    mission: "C",
    energy: 16,
    characters: ["AURRA_SING"],
    gear: [],
  },
  {
    id: `cantina_7d`,
    table: "Cantina",
    difficulty: "",
    map: 7,
    mission: "D",
    energy: 16,
    characters: ["HOTHHAN"],
    gear: [],
  },
  {
    id: `cantina_7e`,
    table: "Cantina",
    difficulty: "",
    map: 7,
    mission: "E",
    energy: 16,
    characters: ["DASHRENDAR"],
    gear: [],
  },
  {
    id: `cantina_7f`,
    table: "Cantina",
    difficulty: "",
    map: 7,
    mission: "F",
    energy: 16,
    characters: ["STAP", "BLADEOFDORIN"],
    gear: [],
  },
  {
    id: `cantina_7g`,
    table: "Cantina",
    difficulty: "",
    map: 7,
    mission: "G",
    energy: 16,
    characters: ["DARTHTALON"],
    gear: [],
  },
  {
    id: `cantina_8a`,
    table: "Cantina",
    difficulty: "",
    map: 8,
    mission: "A",
    energy: 16,
    characters: ["DEATHTROOPER"],
    gear: [],
  },
  {
    id: `cantina_8b`,
    table: "Cantina",
    difficulty: "",
    map: 8,
    mission: "B",
    energy: 16,
    characters: ["SITHTROOPER"],
    gear: [],
  },
  {
    id: `cantina_8c`,
    table: "Cantina",
    difficulty: "",
    map: 8,
    mission: "C",
    energy: 16,
    characters: [],
    gear: [],
  },
  {
    id: `cantina_8d`,
    table: "Cantina",
    difficulty: "",
    map: 8,
    mission: "D",
    energy: 16,
    characters: ["GEONOSIANBROODALPHA"],
    gear: [],
  },
  {
    id: `cantina_8e`,
    table: "Cantina",
    difficulty: "",
    map: 8,
    mission: "E",
    energy: 16,
    characters: ["GREATMOTHERS"],
    gear: [],
  },
  {
    id: `cantina_8f`,
    table: "Cantina",
    difficulty: "",
    map: 8,
    mission: "F",
    energy: 16,
    characters: [],
    gear: [],
  },
  {
    id: `cantina_8g`,
    table: "Cantina",
    difficulty: "",
    map: 8,
    mission: "G",
    energy: 16,
    characters: [],
    gear: [],
  },
];
