const Light = "Light Side";
const light = Light.toLowerCase().replace(" ", "");
const Dark = "Dark Side";
const dark = Dark.toLowerCase().replace(" ", "");
const Fleet = "Fleet";
const fleet = Fleet.toLowerCase().replace(" ", "");
const Cantina = "Cantina";
const cantina = Cantina.toLowerCase().replace(" ", "");

const Normal = "Normal";
const normal = Normal.toLowerCase();
const Hard = "Hard";
const hard = Hard.toLowerCase();

module.exports = [
  {
    id: `${light}_${hard}_1a`,
    table: Light,
    difficulty: Hard,
    map: 1,
    mission: "A",
    energy: 12,
    characters: ["REY"],
    gear: [
      {
        id: "002",
        dropRate: 1,
      },
      {
        id: "004",
        dropRate: 1,
      },
      {
        id: "005",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_1b`,
    table: Light,
    difficulty: Hard,
    map: 1,
    mission: "B",
    energy: 12,
    characters: ["AHSOKATANO"],
    gear: [
      {
        id: "002",
        dropRate: 1,
      },
      {
        id: "007",
        dropRate: 1,
      },
      {
        id: "011",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_1c`,
    table: Light,
    difficulty: Hard,
    map: 1,
    mission: "C",
    energy: 12,
    characters: ["DARKTROOPER"],
    gear: [
      {
        id: "012",
        dropRate: 1,
      },
      {
        id: "009",
        dropRate: 1,
      },
      {
        id: "001",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_1d`,
    table: Light,
    difficulty: Hard,
    map: 1,
    mission: "D",
    energy: 12,
    characters: ["KYLORENUNMASKED"],
    gear: [
      {
        id: "002",
        dropRate: 1,
      },
      {
        id: "003",
        dropRate: 1,
      },
      {
        id: "008",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_2a`,
    table: Light,
    difficulty: Hard,
    map: 2,
    mission: "A",
    energy: 12,
    characters: ["EWOKSCOUT"],
    gear: [
      {
        id: "006",
        dropRate: 1,
      },
      {
        id: "014Prototype",
        dropRate: 1,
      },
      {
        id: "010",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_2b`,
    table: Light,
    difficulty: Hard,
    map: 2,
    mission: "B",
    energy: 12,
    characters: ["FIRSTORDERTROOPER"],
    gear: [
      {
        id: "019",
        dropRate: 1,
      },
      {
        id: "002",
        dropRate: 1,
      },
      {
        id: "017Prototype",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_2c`,
    table: Light,
    difficulty: Hard,
    map: 2,
    mission: "C",
    characters: ["EWOKELDER"],
    gear: [
      {
        id: "007",
        dropRate: 1,
      },
      {
        id: "008",
        dropRate: 1,
      },
      {
        id: "001",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_2d`,
    table: Light,
    difficulty: Hard,
    map: 2,
    mission: "D",
    characters: ["MOFFGIDEONS1"],
    gear: [
      {
        id: "033",
        dropRate: 1,
      },
      {
        id: "004",
        dropRate: 1,
      },
      {
        id: "021",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_2e`,
    table: Light,
    difficulty: Hard,
    map: 2,
    mission: "E",
    characters: ["MACEWINDU"],
    gear: [
      {
        id: "020",
        dropRate: 1,
      },
      {
        id: "009",
        dropRate: 1,
      },
      {
        id: "001",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_2f`,
    table: Light,
    difficulty: Hard,
    map: 2,
    mission: "F",
    characters: ["TALIA"],
    gear: [
      {
        id: "035",
        dropRate: 1,
      },
      {
        id: "003",
        dropRate: 1,
      },
      {
        id: "015Prototype",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_3a`,
    table: Light,
    difficulty: Hard,
    map: 3,
    mission: "A",
    characters: ["RESISTANCETROOPER"],
    gear: [
      {
        id: "050Salvage",
        dropRate: 1,
      },
      {
        id: "016",
        dropRate: 1,
      },
      {
        id: "001",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_3b`,
    table: Light,
    difficulty: Hard,
    map: 3,
    mission: "B",
    characters: ["IG11"],
    gear: [
      {
        id: "034",
        dropRate: 1,
      },
      {
        id: "030",
        dropRate: 1,
      },
      {
        id: "006",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_3c`,
    table: Light,
    difficulty: Hard,
    map: 3,
    mission: "C",
    characters: ["STORMTROOPER"],
    gear: [
      {
        id: "025",
        dropRate: 1,
      },
      {
        id: "004",
        dropRate: 1,
      },
      {
        id: "013",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_3d`,
    table: Light,
    difficulty: Hard,
    map: 3,
    mission: "D",
    characters: ["NINTHSISTER"],
    gear: [
      {
        id: "036",
        dropRate: 1,
      },
      {
        id: "031Prototype",
        dropRate: 1,
      },
      {
        id: "013",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_3e`,
    table: Light,
    difficulty: Hard,
    map: 3,
    mission: "E",
    characters: ["GREEFKARGA"],
    gear: [
      {
        id: "057Salvage",
        dropRate: 1,
      },
      {
        id: "015",
        dropRate: 1,
      },
      {
        id: "009",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_3f`,
    table: Light,
    difficulty: Hard,
    map: 3,
    mission: "F",
    characters: ["DATHCHA"],
    gear: [
      {
        id: "028Prototype",
        dropRate: 1,
      },
      {
        id: "012",
        dropRate: 1,
      },
      {
        id: "005",
        dropRate: 1,
      },
      {
        id: "010",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_4a`,
    table: Light,
    difficulty: Hard,
    map: 4,
    mission: "A",
    characters: ["TEEBO"],
    gear: [
      {
        id: "078Prototype",
        dropRate: 1,
      },
      {
        id: "069Prototype",
        dropRate: 1,
      },
      {
        id: "015Prototype",
        dropRate: 1,
      },
      {
        id: "010",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_4b`,
    table: Light,
    difficulty: Hard,
    map: 4,
    mission: "B",
    characters: ["LOBOT"],
    gear: [
      {
        id: "055Prototype",
        dropRate: 1,
      },
      {
        id: "052Salvage",
        dropRate: 1,
      },
      {
        id: "007",
        dropRate: 1,
      },
      {
        id: "017Prototype",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_4c`,
    table: Light,
    difficulty: Hard,
    map: 4,
    mission: "C",
    characters: ["VEERS"],
    gear: [
      {
        id: "055PrototypeSalvage",
        dropRate: 1,
      },
      {
        id: "040Prototype",
        dropRate: 1,
      },
      {
        id: "013",
        dropRate: 1,
      },
      {
        id: "007",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_4d`,
    table: Light,
    difficulty: Hard,
    map: 4,
    mission: "D",
    characters: ["IDENVERSIOEMPIRE", "VULTUREDROID"],
    gear: [
      {
        id: "051Salvage",
        dropRate: 1,
      },
      {
        id: "044Prototype",
        dropRate: 1,
      },
      {
        id: "009",
        dropRate: 1,
      },
      {
        id: "021Prototype",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_4e`,
    table: Light,
    difficulty: Hard,
    map: 4,
    mission: "E",
    characters: ["POGGLETHELESSER"],
    gear: [
      {
        id: "062Salvage",
        dropRate: 1,
      },
      {
        id: "049Prototype",
        dropRate: 1,
      },
      {
        id: "003",
        dropRate: 1,
      },
      {
        id: "008",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_4f`,
    table: Light,
    difficulty: Hard,
    map: 4,
    mission: "F",
    characters: ["ROSETICO"],
    gear: [
      {
        id: "053Salvage",
        dropRate: 1,
      },
      {
        id: "035",
        dropRate: 1,
      },
      {
        id: "036",
        dropRate: 1,
      },
      {
        id: "001",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_5a`,
    table: Light,
    difficulty: Hard,
    map: 5,
    mission: "A",
    characters: ["URORRURRR"],
    gear: [
      {
        id: "051Salvage",
        dropRate: 1,
      },
      {
        id: "062Salvage",
        dropRate: 1,
      },
      {
        id: "071PrototypeSalvage",
        dropRate: 1,
      },
      {
        id: "027",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_5b`,
    table: Light,
    difficulty: Hard,
    map: 5,
    mission: "B",
    characters: ["BADBATCHHUNTER"],
    gear: [
      {
        id: "086PrototypeSalvage",
        dropRate: 1,
      },
      { id: "028Prototype", dropRate: 1 },
      {
        id: "061Prototype",
        dropRate: 1,
      },
      {
        id: "095Salvage",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_5c`,
    table: Light,
    difficulty: Hard,
    map: 5,
    mission: "C",
    characters: ["CLONESERGEANTPHASEI"],
    gear: [
      {
        id: "091Salvage",
        dropRate: 1,
      },
      {
        id: "071PrototypeSalvage",
        dropRate: 1,
      },
      {
        id: "033",
        dropRate: 1,
      },
      {
        id: "030",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_5d`,
    table: Light,
    difficulty: Hard,
    map: 5,
    mission: "D",
    characters: ["ZAALBAR"],
    gear: [
      {
        id: "097PrototypeSalvage",
        dropRate: 1,
      },
      {
        id: "054Salvage",
        dropRate: 1,
      },
      {
        id: "027",
        dropRate: 1,
      },
      {
        id: "025",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_5e`,
    table: Light,
    difficulty: Hard,
    map: 5,
    mission: "E",
    characters: ["MONMOTHMA"],
    gear: [
      {
        id: "084PrototypeSalvage",
        dropRate: 1,
      },
      {
        id: "085PrototypeSalvage",
        dropRate: 1,
      },
      {
        id: "034",
        dropRate: 1,
      },
      {
        id: "031Prototype",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_5f`,
    table: Light,
    difficulty: Hard,
    map: 5,
    mission: "F",
    characters: ["BADBATCHTECH"],
    gear: [
      {
        id: "101Salvage",
        dropRate: 1,
      },
      {
        id: "052Salvage",
        dropRate: 1,
      },
      {
        id: "066",
        dropRate: 1,
      },
      {
        id: "004",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_6a`,
    table: Light,
    difficulty: Hard,
    map: 6,
    mission: "A",
    characters: ["JUHANI"],
    gear: [
      {
        id: "100PrototypeSalvage",
        dropRate: 1,
      },
      {
        id: "102Salvage",
        dropRate: 1,
      },
      {
        id: "076Salvage",
        dropRate: 1,
      },
      {
        id: "093PrototypeSalvage",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_6b`,
    table: Light,
    difficulty: Hard,
    map: 6,
    mission: "B",
    characters: ["ADMIRALPIETT", "EPIXPOE"],
    gear: [
      {
        id: "090PrototypeSalvage",
        dropRate: 1,
      },
      {
        id: "103PrototypeSalvage",
        dropRate: 1,
      },
      {
        id: "057Salvage",
        dropRate: 1,
      },
      {
        id: "071PrototypeSalvage",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_6c`,
    table: Light,
    difficulty: Hard,
    map: 6,
    mission: "C",
    characters: ["FENNECSHAND", "SITHBOMBER"],
    gear: [
      {
        id: "104PrototypeSalvage",
        dropRate: 1,
      },
      {
        id: "050Salvage",
        dropRate: 1,
      },
      {
        id: "078PrototypeSalvage",
        dropRate: 1,
      },
      {
        id: "095Salvage",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${light}_${hard}_6d`,
    table: Light,
    difficulty: Hard,
    map: 6,
    mission: "D",
    characters: ["MARAJADE"],
    gear: [],
  },
  {
    id: `${light}_${hard}_6e`,
    table: Light,
    difficulty: Hard,
    map: 6,
    mission: "E",
    characters: ["EIGHTHBROTHER", "IG2000"],
    gear: [],
  },
  {
    id: `${light}_${hard}_7a`,
    table: Light,
    difficulty: Hard,
    map: 7,
    mission: "A",
    characters: ["C3POCHEWBACCA"],
    gear: [],
  },
  {
    id: `${light}_${hard}_7b`,
    table: Light,
    difficulty: Hard,
    map: 7,
    mission: "B",
    characters: ["POE"],
    gear: [],
  },
  {
    id: `${light}_${hard}_7c`,
    table: Light,
    difficulty: Hard,
    map: 7,
    mission: "C",
    characters: ["BADBATCHWRECKER", "YWINGCLONEWARS"],
    gear: [],
  },
  {
    id: `${light}_${hard}_7d`,
    table: Light,
    difficulty: Hard,
    map: 7,
    mission: "D",
    characters: ["BADBATCHECHO", "LUKESKYWALKER"],
    gear: [],
  },
  {
    id: `${light}_${hard}_8a`,
    table: Light,
    difficulty: Hard,
    map: 8,
    mission: "A",
    characters: ["MOTHERTALZIN"],
    gear: [],
  },
  {
    id: `${light}_${hard}_8b`,
    table: Light,
    difficulty: Hard,
    map: 8,
    mission: "B",
    characters: ["DROIDEKA", "XANADUBLOOD"],
    gear: [],
  },
  {
    id: `${light}_${hard}_8c`,
    table: Light,
    difficulty: Hard,
    map: 8,
    mission: "C",
    characters: ["EPIXFINN", "SNOWTROOPER"],
    gear: [],
  },
  {
    id: `${light}_${hard}_8d`,
    table: Light,
    difficulty: Hard,
    map: 8,
    mission: "D",
    characters: ["JANGOFETT", "HOUNDSTOOTH"],
    gear: [],
  },
  {
    id: `${light}_${hard}_9a`,
    table: Light,
    difficulty: Hard,
    map: 9,
    mission: "A",
    characters: ["DARTHSION", "COMMANDSHUTTLE"],
    gear: [],
  },
  {
    id: `${light}_${hard}_9b`,
    table: Light,
    difficulty: Hard,
    map: 9,
    mission: "A",
    characters: ["SHORETROOPER", "TIEREAPER"],
    gear: [],
  },
  {
    id: `${light}_${hard}_9c`,
    table: Light,
    difficulty: Hard,
    map: 9,
    mission: "C",
    characters: ["ARMORER", "BAZEMALBUS"],
    gear: [],
  },
  {
    id: `${light}_${hard}_9d`,
    table: Light,
    difficulty: Hard,
    map: 9,
    mission: "D",
    characters: ["DIRECTORKRENNIC", "GEONOSIANSTARFIGHTER2"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_1a`,
    table: Dark,
    difficulty: Hard,
    map: 1,
    mission: "A",
    characters: ["SABINEWRENS3"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_1b`,
    table: Dark,
    difficulty: Hard,
    map: 1,
    mission: "B",
    characters: ["ANAKINKNIGHT"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_1c`,
    table: Dark,
    difficulty: Hard,
    map: 1,
    mission: "C",
    characters: ["COUNTDOOKU"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_1d`,
    table: Dark,
    difficulty: Hard,
    map: 1,
    mission: "D",
    characters: ["JEDIKNIGHTCONSULAR"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_2a`,
    table: Dark,
    difficulty: Hard,
    map: 2,
    mission: "A",
    characters: ["FIRSTORDERTROOPER"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_2b`,
    table: Dark,
    difficulty: Hard,
    map: 2,
    mission: "B",
    characters: ["BOBAFETT"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_2c`,
    table: Dark,
    difficulty: Hard,
    map: 2,
    mission: "C",
    characters: ["OLDBENKENOBI"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_2d`,
    table: Dark,
    difficulty: Hard,
    map: 2,
    mission: "D",
    energy: 12,
    characters: ["CT5555"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_2e`,
    table: Dark,
    difficulty: Hard,
    map: 2,
    mission: "E",
    energy: 12,
    characters: ["LUMINARAUNDULI"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_2f`,
    table: Dark,
    difficulty: Hard,
    map: 2,
    mission: "F",
    energy: 12,
    characters: ["IG86SENTINELDROID"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_3a`,
    table: Dark,
    difficulty: Hard,
    map: 3,
    mission: "A",
    energy: 12,
    characters: ["RANGETROOPER"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_3b`,
    table: Dark,
    difficulty: Hard,
    map: 3,
    mission: "B",
    energy: 12,
    characters: ["HOTHREBELSCOUT"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_3c`,
    table: Dark,
    difficulty: Hard,
    map: 3,
    mission: "C",
    energy: 12,
    characters: ["THEMANDALORIAN"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_3d`,
    table: Dark,
    difficulty: Hard,
    map: 3,
    mission: "D",
    energy: 12,
    characters: ["TEEBO"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_3e`,
    table: Dark,
    difficulty: Hard,
    map: 3,
    mission: "E",
    energy: 12,
    characters: ["50RT"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_3f`,
    table: Dark,
    difficulty: Hard,
    map: 3,
    mission: "F",
    energy: 12,
    characters: ["JEDIKNIGHTGUARDIAN"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_4a`,
    table: Dark,
    difficulty: Hard,
    map: 4,
    mission: "A",
    energy: 12,
    characters: ["BIGGSDARKLIGHTER"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_4b`,
    table: Dark,
    difficulty: Hard,
    map: 4,
    mission: "B",
    energy: 12,
    characters: ["DAKA"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_4c`,
    table: Dark,
    difficulty: Hard,
    map: 4,
    mission: "C",
    energy: 12,
    characters: ["SECONDSISTER"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_4d`,
    table: Dark,
    difficulty: Hard,
    map: 4,
    mission: "D",
    energy: 12,
    characters: ["YOUNGCHEWBACCA"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_4e`,
    table: Dark,
    difficulty: Hard,
    map: 4,
    mission: "E",
    energy: 12,
    characters: ["SEVENTHSISTER"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_4f`,
    table: Dark,
    difficulty: Hard,
    map: 4,
    mission: "F",
    energy: 12,
    characters: ["JAWA"],
    gear: [
      {
        id: "006",
        dropRate: 1,
      },
    ],
  },
  {
    id: `${dark}_${hard}_5a`,
    table: Dark,
    difficulty: Hard,
    map: 5,
    mission: "A",
    energy: 16,
    characters: ["KUIIL", "TIEBOMBERIMPERIAL"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_5b`,
    table: Dark,
    difficulty: Hard,
    map: 5,
    mission: "B",
    energy: 16,
    characters: ["BASTILASHAN"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_5c`,
    table: Dark,
    difficulty: Hard,
    map: 5,
    mission: "C",
    energy: 16,
    characters: ["BARRISSOFFEE", "IMAGUNDI"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_5d`,
    table: Dark,
    difficulty: Hard,
    map: 5,
    mission: "D",
    energy: 16,
    characters: ["REY", "MILLENNIUMFALCONEP7"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_5e`,
    table: Dark,
    difficulty: Hard,
    map: 5,
    mission: "E",
    energy: 16,
    characters: ["CARADUNE"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_5f`,
    table: Dark,
    difficulty: Hard,
    map: 5,
    mission: "F",
    energy: 16,
    characters: ["ROYALGUARD"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_6a`,
    table: Dark,
    difficulty: Hard,
    map: 6,
    mission: "A",
    energy: 16,
    characters: ["GENERALHUX", "HOTHREBELSCOUT"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_6b`,
    table: Dark,
    difficulty: Hard,
    map: 6,
    mission: "B",
    energy: 16,
    characters: ["FIRSTORDERTIEPILOT"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_6c`,
    table: Dark,
    difficulty: Hard,
    map: 6,
    mission: "C",
    energy: 16,
    characters: ["FOSITHTROOPER", "TUSKENRAIDER"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_6d`,
    table: Dark,
    difficulty: Hard,
    map: 6,
    mission: "D",
    energy: 16,
    characters: ["BOKATAN", "JOLEEBINDO"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_6e`,
    table: Dark,
    difficulty: Hard,
    map: 6,
    mission: "E",
    energy: 16,
    characters: ["MAGNAGUARD"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_7a`,
    table: Dark,
    difficulty: Hard,
    map: 7,
    mission: "A",
    energy: 20,
    characters: ["BASTILASHANDARK"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_7b`,
    table: Dark,
    difficulty: Hard,
    map: 7,
    mission: "B",
    energy: 20,
    characters: ["VISASMARR"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_7c`,
    table: Dark,
    difficulty: Hard,
    map: 7,
    mission: "C",
    energy: 20,
    characters: ["AMILYNHOLDO"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_7d`,
    table: Dark,
    difficulty: Hard,
    map: 7,
    mission: "D",
    energy: 20,
    characters: ["EMPERORSSHUTTLE"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_8a`,
    table: Dark,
    difficulty: Hard,
    map: 8,
    mission: "A",
    energy: 20,
    characters: ["WICKET"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_8b`,
    table: Dark,
    difficulty: Hard,
    map: 8,
    mission: "B",
    energy: 20,
    characters: ["HYENABOMBER", "JEDISTARFIGHTERCONSULAR"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_8c`,
    table: Dark,
    difficulty: Hard,
    map: 8,
    mission: "C",
    energy: 20,
    characters: ["EMBO"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_8d`,
    table: Dark,
    difficulty: Hard,
    map: 8,
    mission: "D",
    energy: 20,
    characters: ["NIGHTSISTERZOMBIE"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_9a`,
    table: Dark,
    difficulty: Hard,
    map: 9,
    mission: "A",
    energy: 20,
    characters: ["DARTHNIHILUS"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_9b`,
    table: Dark,
    difficulty: Hard,
    map: 9,
    mission: "B",
    energy: 20,
    characters: ["BOSSK"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_9c`,
    table: Dark,
    difficulty: Hard,
    map: 9,
    mission: "C",
    energy: 20,
    characters: ["GHOST"],
    gear: [],
  },
  {
    id: `${dark}_${hard}_9d`,
    table: Dark,
    difficulty: Hard,
    map: 9,
    mission: "D",
    energy: 20,
    characters: ["PHANTOM2"],
    gear: [],
  },
  {
    id: `${fleet}_${hard}_1a`,
    table: Fleet,
    difficulty: Hard,
    map: 1,
    mission: "A",
    energy: 16,
    characters: ["ARC170CLONESERGEANT"],
    gear: [],
  },
  {
    id: `${fleet}_${hard}_1b`,
    table: Fleet,
    difficulty: Hard,
    map: 1,
    mission: "B",
    energy: 16,
    characters: ["JEDISTARFIGHTERANAKIN"],
    gear: [],
  },
  {
    id: `${fleet}_${hard}_1c`,
    table: Fleet,
    difficulty: Hard,
    map: 1,
    mission: "C",
    energy: 16,
    characters: ["TIEFIGHTERIMPERIAL"],
    gear: [],
  },
  {
    id: `${fleet}_${hard}_1d`,
    table: Fleet,
    difficulty: Hard,
    map: 1,
    mission: "D",
    energy: 16,
    characters: ["YOUNGLANDO", "MILLENNIUMFALCONPRISTINE"],
    gear: [],
  },
  {
    id: `${fleet}_${hard}_1d`,
    table: Fleet,
    difficulty: Hard,
    map: 1,
    mission: "D",
    energy: 16,
    characters: ["XWINGRESISTANCE"],
    gear: [],
  },
  {
    id: `${fleet}_${hard}_2a`,
    table: Fleet,
    difficulty: Hard,
    map: 2,
    mission: "A",
    energy: 20,
    characters: ["GEONOSIANSTARFIGHTER1"],
    gear: [],
  },
  {
    id: `${fleet}_${hard}_2b`,
    table: Fleet,
    difficulty: Hard,
    map: 2,
    mission: "B",
    energy: 20,
    characters: ["SLAVE1"],
    gear: [],
  },
  {
    id: `${fleet}_${hard}_2c`,
    table: Fleet,
    difficulty: Hard,
    map: 2,
    mission: "C",
    energy: 20,
    characters: ["UWINGSCARIF"],
    gear: [],
  },
  {
    id: `${fleet}_${hard}_2d`,
    table: Fleet,
    difficulty: Hard,
    map: 2,
    mission: "D",
    energy: 20,
    characters: ["MG100STARFORTRESSSF17"],
    gear: [],
  },
  {
    id: `${fleet}_${hard}_2e`,
    table: Fleet,
    difficulty: Hard,
    map: 2,
    mission: "E",
    energy: 20,
    characters: ["CARTHONASI"],
    gear: [],
  },
  {
    id: `${fleet}_${hard}_3a`,
    table: Fleet,
    difficulty: Hard,
    map: 3,
    mission: "A",
    energy: 20,
    characters: ["XWINGBLACKONE"],
    gear: [],
  },
  {
    id: `${fleet}_${hard}_3b`,
    table: Fleet,
    difficulty: Hard,
    map: 3,
    mission: "B",
    energy: 20,
    characters: ["UMBARANSTARFIGHTER"],
    gear: [],
  },
  {
    id: `${fleet}_${hard}_3c`,
    table: Fleet,
    difficulty: Hard,
    map: 3,
    mission: "C",
    energy: 20,
    characters: ["OUTRIDER"],
    gear: [],
  },
  {
    id: `${fleet}_${hard}_3d`,
    table: Fleet,
    difficulty: Hard,
    map: 3,
    mission: "D",
    energy: 20,
    characters: ["SITHINFILTRATOR"],
    gear: [],
  },
  {
    id: `${fleet}_${hard}_3e`,
    table: Fleet,
    difficulty: Hard,
    map: 3,
    mission: "E",
    energy: 20,
    characters: ["SITHFIGHTER"],
    gear: [],
  },
  {
    id: `${fleet}_${hard}_4a`,
    table: Fleet,
    difficulty: Hard,
    map: 4,
    mission: "A",
    energy: 20,
    characters: ["GAUNTLETSTARFIGHTER"],
    gear: [],
  },
  {
    id: `${fleet}_${hard}_4b`,
    table: Fleet,
    difficulty: Hard,
    map: 4,
    mission: "B",
    energy: 20,
    characters: ["TIEADVANCED"],
    gear: [],
  },
  {
    id: `${fleet}_${hard}_4c`,
    table: Fleet,
    difficulty: Hard,
    map: 4,
    mission: "C",
    energy: 20,
    characters: ["GREEFKARGA", "YWINGREBEL"],
    gear: [],
  },
  {
    id: `${fleet}_${hard}_4d`,
    table: Fleet,
    difficulty: Hard,
    map: 4,
    mission: "D",
    energy: 20,
    characters: ["BADBATCHOMEGA"],
    gear: [],
  },
  {
    id: `${fleet}_${hard}_4e`,
    table: Fleet,
    difficulty: Hard,
    map: 4,
    mission: "E",
    energy: 20,
    characters: ["FIRSTORDERTIEECHELON"],
    gear: [],
  },
  {
    id: `${fleet}_${hard}_5a`,
    table: Fleet,
    difficulty: Hard,
    map: 5,
    mission: "A",
    energy: 20,
    characters: ["SHAAKTI"],
    gear: [],
  },
  {
    id: `${fleet}_${hard}_5b`,
    table: Fleet,
    difficulty: Hard,
    map: 5,
    mission: "B",
    energy: 20,
    characters: ["B1BATTLEDROIDV2"],
    gear: [],
  },
  {
    id: `${fleet}_${hard}_5c`,
    table: Fleet,
    difficulty: Hard,
    map: 5,
    mission: "C",
    energy: 20,
    characters: [],
    gear: [],
  },

  {
    id: `${fleet}_${hard}_5d`,
    table: Fleet,
    difficulty: Hard,
    map: 5,
    mission: "D",
    energy: 20,
    characters: ["ENFYSNEST"],
    gear: [],
  },
  {
    id: `${fleet}_${hard}_5e`,
    table: Fleet,
    difficulty: Hard,
    map: 5,
    mission: "E",
    energy: 20,
    characters: ["THEMANDALORIAN"],
    gear: [],
  },
  {
    id: `${fleet}_${hard}_5f`,
    table: Fleet,
    difficulty: Hard,
    map: 5,
    mission: "F",
    energy: 20,
    characters: [],
    gear: [],
  },
  {
    id: `${cantina}_1a`,
    table: Cantina,
    difficulty: "",
    map: 1,
    mission: "A",
    energy: 8,
    characters: ["GEONOSIANSOLDIER"],
    gear: [],
  },
  {
    id: `${cantina}_1b`,
    table: Cantina,
    difficulty: "",
    map: 1,
    mission: "B",
    energy: 8,
    characters: ["LUKESKYWALKER"],
    gear: [],
  },
  {
    id: `${cantina}_1c`,
    table: Cantina,
    difficulty: "",
    map: 1,
    mission: "C",
    energy: 8,
    characters: ["OLDBENKENOBI"],
    gear: [],
  },
  {
    id: `${cantina}_1d`,
    table: Cantina,
    difficulty: "",
    map: 1,
    mission: "D",
    energy: 8,
    characters: ["SCARIFREBEL"],
    gear: [],
  },
  {
    id: `${cantina}_1e`,
    table: Cantina,
    difficulty: "",
    map: 1,
    mission: "E",
    energy: 8,
    characters: ["ADMINISTRATORLANDO"],
    gear: [],
  },
  {
    id: `${cantina}_1f`,
    table: Cantina,
    difficulty: "",
    map: 1,
    mission: "F",
    energy: 8,
    characters: ["HERASYNDULLAS3"],
    gear: [],
  },
  {
    id: `${cantina}_1g`,
    table: Cantina,
    difficulty: "",
    map: 1,
    mission: "G",
    energy: 8,
    characters: ["TALIA"],
    gear: [],
  },
  {
    id: `${cantina}_2a`,
    table: Cantina,
    difficulty: "",
    map: 2,
    mission: "A",
    energy: 8,
    characters: ["NIGHTSISTERACOLYTE"],
    gear: [],
  },
  {
    id: `${cantina}_2b`,
    table: Cantina,
    difficulty: "",
    map: 2,
    mission: "B",
    energy: 8,
    characters: ["EZRABRIDGERS3"],
    gear: [],
  },
  {
    id: `${cantina}_2c`,
    table: Cantina,
    difficulty: "",
    map: 2,
    mission: "C",
    energy: 8,
    characters: ["IMPERIALSUPERCOMMANDO"],
    gear: [],
  },
  {
    id: `${cantina}_2d`,
    table: Cantina,
    difficulty: "",
    map: 2,
    mission: "D",
    energy: 8,
    characters: ["JAWA"],
    gear: [],
  },
  {
    id: `${cantina}_2e`,
    table: Cantina,
    difficulty: "",
    map: 2,
    mission: "E",
    energy: 8,
    characters: ["GARSAXON"],
    gear: [],
  },
  {
    id: `${cantina}_2f`,
    table: Cantina,
    difficulty: "",
    map: 2,
    mission: "F",
    energy: 8,
    characters: ["CLONEWARSCHEWBACCA"],
    gear: [],
  },
  {
    id: `${cantina}_2g`,
    table: Cantina,
    difficulty: "",
    map: 2,
    mission: "G",
    energy: 8,
    characters: ["FIRSTORDEREXECUTIONER"],
    gear: [],
  },
  {
    id: `${cantina}_3a`,
    table: Cantina,
    difficulty: "",
    map: 3,
    mission: "A",
    energy: 10,
    characters: ["JEDIKNIGHTCONSULAR"],
    gear: [],
  },
  {
    id: `${cantina}_3b`,
    table: Cantina,
    difficulty: "",
    map: 3,
    mission: "B",
    energy: 10,
    characters: ["QIRA"],
    gear: [],
  },
  {
    id: `${cantina}_3c`,
    table: Cantina,
    difficulty: "",
    map: 3,
    mission: "C",
    energy: 10,
    characters: ["MAGNAGUARD"],
    gear: [],
  },
  {
    id: `${cantina}_3d`,
    table: Cantina,
    difficulty: "",
    map: 3,
    mission: "D",
    energy: 10,
    characters: ["PAPLOO"],
    gear: [],
  },
  {
    id: `${cantina}_3e`,
    table: Cantina,
    difficulty: "",
    map: 3,
    mission: "E",
    energy: 10,
    characters: ["FINN"],
    gear: [],
  },
  {
    id: `${cantina}_3f`,
    table: Cantina,
    difficulty: "",
    map: 3,
    mission: "F",
    energy: 10,
    characters: ["KYLORENUNMASKED", "TIESILENCER"],
    gear: [],
  },
  {
    id: `${cantina}_3g`,
    table: Cantina,
    difficulty: "",
    map: 3,
    mission: "G",
    energy: 10,
    characters: ["BIGGSDARKLIGHTER"],
    gear: [],
  },
  {
    id: `${cantina}_4a`,
    table: Cantina,
    difficulty: "",
    map: 4,
    mission: "A",
    energy: 10,
    characters: ["FIFTHBROTHER"],
    gear: [],
  },
  {
    id: `${cantina}_4b`,
    table: Cantina,
    difficulty: "",
    map: 4,
    mission: "B",
    energy: 10,
    characters: ["TIEFIGHTERPILOT"],
    gear: [],
  },
  {
    id: `${cantina}_4c`,
    table: Cantina,
    difficulty: "",
    map: 4,
    mission: "C",
    energy: 10,
    characters: ["KYLOREN"],
    gear: [],
  },
  {
    id: `${cantina}_4d`,
    table: Cantina,
    difficulty: "",
    map: 4,
    mission: "D",
    energy: 10,
    characters: ["GEONOSIANSPY"],
    gear: [],
  },
  {
    id: `${cantina}_4e`,
    table: Cantina,
    difficulty: "",
    map: 4,
    mission: "E",
    energy: 10,
    characters: ["MOFFGIDEONS1"],
    gear: [],
  },
  {
    id: `${cantina}_4f`,
    table: Cantina,
    difficulty: "",
    map: 4,
    mission: "F",
    energy: 10,
    characters: ["KITFISTO"],
    gear: [],
  },
  {
    id: `${cantina}_4g`,
    table: Cantina,
    difficulty: "",
    map: 4,
    mission: "G",
    energy: 10,
    characters: ["PLOKOON"],
    gear: [],
  },
  {
    id: `${cantina}_5a`,
    table: Cantina,
    difficulty: "",
    map: 5,
    mission: "A",
    energy: 12,
    characters: ["L3_37"],
    gear: [],
  },
  {
    id: `${cantina}_5b`,
    table: Cantina,
    difficulty: "",
    map: 5,
    mission: "B",
    energy: 12,
    characters: ["AAYLASECURA"],
    gear: [],
  },
  {
    id: `${cantina}_5c`,
    table: Cantina,
    difficulty: "",
    map: 5,
    mission: "C",
    energy: 12,
    characters: ["CANDEROUSORDO"],
    gear: [],
  },
  {
    id: `${cantina}_5d`,
    table: Cantina,
    difficulty: "",
    map: 5,
    mission: "D",
    energy: 12,
    characters: ["CHIEFCHIRPA"],
    gear: [],
  },
  {
    id: `${cantina}_5e`,
    table: Cantina,
    difficulty: "",
    map: 5,
    mission: "E",
    energy: 12,
    characters: ["SMUGGLERHAN"],
    gear: [],
  },
  {
    id: `${cantina}_5f`,
    table: Cantina,
    difficulty: "",
    map: 5,
    mission: "F",
    energy: 12,
    characters: ["SMUGGLERCHEWBACCA"],
    gear: [],
  },
  {
    id: `${cantina}_5g`,
    table: Cantina,
    difficulty: "",
    map: 5,
    mission: "G",
    energy: 12,
    characters: ["ARCTROOPER501ST"],
    gear: [],
  },
  {
    id: `${cantina}_6a`,
    table: Cantina,
    difficulty: "",
    map: 6,
    mission: "A",
    energy: 12,
    characters: ["KYLEKATARN"],
    gear: [],
  },
  {
    id: `${cantina}_6b`,
    table: Cantina,
    difficulty: "",
    map: 6,
    mission: "B",
    energy: 12,
    characters: ["T3_M4"],
    gear: [],
  },
  {
    id: `${cantina}_6c`,
    table: Cantina,
    difficulty: "",
    map: 6,
    mission: "C",
    energy: 12,
    characters: ["SITHASSASSIN"],
    gear: [],
  },
  {
    id: `${cantina}_6d`,
    table: Cantina,
    difficulty: "",
    map: 6,
    mission: "D",
    energy: 12,
    characters: ["B2SUPERBATTLEDROID"],
    gear: [],
  },
  {
    id: `${cantina}_6e`,
    table: Cantina,
    difficulty: "",
    map: 6,
    mission: "E",
    energy: 12,
    characters: ["SITHMARAUDER"],
    gear: [],
  },
  {
    id: `${cantina}_6f`,
    table: Cantina,
    difficulty: "",
    map: 6,
    mission: "F",
    energy: 12,
    characters: ["WEDGEANTILLES"],
    gear: [],
  },
  {
    id: `${cantina}_6g`,
    table: Cantina,
    difficulty: "",
    map: 6,
    mission: "G",
    energy: 12,
    characters: ["COUNTDOOKU"],
    gear: [],
  },
  {
    id: `${cantina}_7a`,
    table: Cantina,
    difficulty: "",
    map: 7,
    mission: "A",
    energy: 16,
    characters: ["MISSIONVAO"],
    gear: [],
  },
  {
    id: `${cantina}_7b`,
    table: Cantina,
    difficulty: "",
    map: 7,
    mission: "B",
    energy: 16,
    characters: ["SNOWTROOPER"],
    gear: [],
  },
  {
    id: `${cantina}_7c`,
    table: Cantina,
    difficulty: "",
    map: 7,
    mission: "C",
    energy: 16,
    characters: ["AURRA_SING"],
    gear: [],
  },
  {
    id: `${cantina}_7d`,
    table: Cantina,
    difficulty: "",
    map: 7,
    mission: "D",
    energy: 16,
    characters: ["HOTHHAN"],
    gear: [],
  },
  {
    id: `${cantina}_7e`,
    table: Cantina,
    difficulty: "",
    map: 7,
    mission: "E",
    energy: 16,
    characters: ["DASHRENDAR"],
    gear: [],
  },
  {
    id: `${cantina}_7f`,
    table: Cantina,
    difficulty: "",
    map: 7,
    mission: "F",
    energy: 16,
    characters: ["NIGHTSISTERSPIRIT", "BLADEOFDORIN"],
    gear: [],
  },
  {
    id: `${cantina}_7g`,
    table: Cantina,
    difficulty: "",
    map: 7,
    mission: "G",
    energy: 16,
    characters: ["DARTHTALON"],
    gear: [],
  },
  {
    id: `${cantina}_8a`,
    table: Cantina,
    difficulty: "",
    map: 8,
    mission: "A",
    energy: 16,
    characters: ["DEATHTROOPER"],
    gear: [],
  },
  {
    id: `${cantina}_8b`,
    table: Cantina,
    difficulty: "",
    map: 8,
    mission: "B",
    energy: 16,
    characters: ["SITHTROOPER"],
    gear: [],
  },
  {
    id: `${cantina}_8c`,
    table: Cantina,
    difficulty: "",
    map: 8,
    mission: "C",
    energy: 16,
    characters: [],
    gear: [],
  },
  {
    id: `${cantina}_8d`,
    table: Cantina,
    difficulty: "",
    map: 8,
    mission: "D",
    energy: 16,
    characters: ["GEONOSIANBROODALPHA"],
    gear: [],
  },
  {
    id: `${cantina}_8e`,
    table: Cantina,
    difficulty: "",
    map: 8,
    mission: "E",
    energy: 16,
    characters: ["EBONHAWK"],
    gear: [],
  },
  {
    id: `${cantina}_8f`,
    table: Cantina,
    difficulty: "",
    map: 8,
    mission: "F",
    energy: 16,
    characters: [],
    gear: [],
  },
  {
    id: `${cantina}_8g`,
    table: Cantina,
    difficulty: "",
    map: 8,
    mission: "G",
    energy: 16,
    characters: [],
    gear: [],
  },
];
