const Light = "Light Side";
const light = Light.toLowerCase().replace(" ", "");
const Dark = "Dark Side";
const dark = Dark.toLowerCase().replace(" ", "");
const Fleet = "Fleet";
const fleet = Fleet.toLowerCase().replace(" ", "");
const Cantina = "Cantina";
const cantina = Cantina.toLowerCase().replace(" ", "");

const Normal = "Normal";
const normal = Normal.toLowerCase();
const Hard = "Hard";
const hard = Hard.toLowerCase();

module.exports = [
  {
    id: `${light}_${normal}_1a`,
    table: Light,
    difficulty: Normal,
    map: 1,
    mission: "A",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_1b`,
    table: Light,
    difficulty: Normal,
    map: 1,
    mission: "B",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_1c`,
    table: Light,
    difficulty: Normal,
    map: 1,
    mission: "C",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_1d`,
    table: Light,
    difficulty: Normal,
    map: 1,
    mission: "D",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_1e`,
    table: Light,
    difficulty: Normal,
    map: 1,
    mission: "E",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_1f`,
    table: Light,
    difficulty: Normal,
    map: 1,
    mission: "F",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_2a`,
    table: Light,
    difficulty: Normal,
    map: 2,
    mission: "A",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_2b`,
    table: Light,
    difficulty: Normal,
    map: 2,
    mission: "B",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_2c`,
    table: Light,
    difficulty: Normal,
    map: 2,
    mission: "C",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_2d`,
    table: Light,
    difficulty: Normal,
    map: 2,
    mission: "D",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_2e`,
    table: Light,
    difficulty: Normal,
    map: 2,
    mission: "E",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_2f`,
    table: Light,
    difficulty: Normal,
    map: 2,
    mission: "F",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_2g`,
    table: Light,
    difficulty: Normal,
    map: 2,
    mission: "G",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_2h`,
    table: Light,
    difficulty: Normal,
    map: 2,
    mission: "H",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_2i`,
    table: Light,
    difficulty: Normal,
    map: 2,
    mission: "I",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_3a`,
    table: Light,
    difficulty: Normal,
    map: 3,
    mission: "A",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_3b`,
    table: Light,
    difficulty: Normal,
    map: 3,
    mission: "B",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_3c`,
    table: Light,
    difficulty: Normal,
    map: 3,
    mission: "C",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_3d`,
    table: Light,
    difficulty: Normal,
    map: 3,
    mission: "D",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_3e`,
    table: Light,
    difficulty: Normal,
    map: 3,
    mission: "E",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_3f`,
    table: Light,
    difficulty: Normal,
    map: 3,
    mission: "F",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_3g`,
    table: Light,
    difficulty: Normal,
    map: 3,
    mission: "G",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_3h`,
    table: Light,
    difficulty: Normal,
    map: 3,
    mission: "H",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_3i`,
    table: Light,
    difficulty: Normal,
    map: 3,
    mission: "I",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_4a`,
    table: Light,
    difficulty: Normal,
    map: 4,
    mission: "A",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_4b`,
    table: Light,
    difficulty: Normal,
    map: 4,
    mission: "B",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_4c`,
    table: Light,
    difficulty: Normal,
    map: 4,
    mission: "C",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_4d`,
    table: Light,
    difficulty: Normal,
    map: 4,
    mission: "D",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_4e`,
    table: Light,
    difficulty: Normal,
    map: 4,
    mission: "E",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_4f`,
    table: Light,
    difficulty: Normal,
    map: 4,
    mission: "F",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_4g`,
    table: Light,
    difficulty: Normal,
    map: 4,
    mission: "G",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_4h`,
    table: Light,
    difficulty: Normal,
    map: 4,
    mission: "H",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_4i`,
    table: Light,
    difficulty: Normal,
    map: 4,
    mission: "I",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_4j`,
    table: Light,
    difficulty: Normal,
    map: 4,
    mission: "J",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_4k`,
    table: Light,
    difficulty: Normal,
    map: 4,
    mission: "K",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_4l`,
    table: Light,
    difficulty: Normal,
    map: 4,
    mission: "L",
    energy: 6,
    characters: [],
  },
  {
    id: `${light}_${normal}_5a`,
    table: Light,
    difficulty: Normal,
    map: 5,
    mission: "A",
    energy: 8,
    characters: [],
  },
  {
    id: `${light}_${normal}_5a`,
    table: Light,
    difficulty: Normal,
    map: 5,
    mission: "A",
    energy: 8,
    characters: [],
  },
  {
    id: `${light}_${normal}_5b`,
    table: Light,
    difficulty: Normal,
    map: 5,
    mission: "B",
    energy: 8,
    characters: [],
  },
  {
    id: `${light}_${normal}_5c`,
    table: Light,
    difficulty: Normal,
    map: 5,
    mission: "C",
    energy: 8,
    characters: [],
  },
  {
    id: `${light}_${normal}_5d`,
    table: Light,
    difficulty: Normal,
    map: 5,
    mission: "D",
    energy: 8,
    characters: [],
  },
  {
    id: `${light}_${normal}_5e`,
    table: Light,
    difficulty: Normal,
    map: 5,
    mission: "E",
    energy: 8,
    characters: [],
  },
  {
    id: `${light}_${normal}_5f`,
    table: Light,
    difficulty: Normal,
    map: 5,
    mission: "F",
    energy: 8,
    characters: [],
  },
  {
    id: `${light}_${normal}_5g`,
    table: Light,
    difficulty: Normal,
    map: 5,
    mission: "G",
    energy: 8,
    characters: [],
  },
  {
    id: `${light}_${normal}_5h`,
    table: Light,
    difficulty: Normal,
    map: 5,
    mission: "H",
    energy: 8,
    characters: [],
  },
  {
    id: `${light}_${normal}_5i`,
    table: Light,
    difficulty: Normal,
    map: 5,
    mission: "I",
    energy: 8,
    characters: [],
  },
  {
    id: `${light}_${normal}_5j`,
    table: Light,
    difficulty: Normal,
    map: 5,
    mission: "J",
    energy: 8,
    characters: [],
  },
  {
    id: `${light}_${normal}_5k`,
    table: Light,
    difficulty: Normal,
    map: 5,
    mission: "K",
    energy: 8,
    characters: [],
  },
  {
    id: `${light}_${normal}_5l`,
    table: Light,
    difficulty: Normal,
    map: 5,
    mission: "L",
    energy: 8,
    characters: [],
  },
  {
    id: `${light}_${normal}_6a`,
    table: Light,
    difficulty: Normal,
    map: 6,
    mission: "A",
    energy: 8,
    characters: [],
  },
  {
    id: `${light}_${normal}_6b`,
    table: Light,
    difficulty: Normal,
    map: 6,
    mission: "B",
    energy: 8,
    characters: [],
  },
  {
    id: `${light}_${normal}_6c`,
    table: Light,
    difficulty: Normal,
    map: 6,
    mission: "C",
    energy: 8,
    characters: [],
  },
  {
    id: `${light}_${normal}_6d`,
    table: Light,
    difficulty: Normal,
    map: 6,
    mission: "D",
    energy: 8,
    characters: [],
  },
  {
    id: `${light}_${normal}_6e`,
    table: Light,
    difficulty: Normal,
    map: 6,
    mission: "E",
    energy: 8,
    characters: [],
  },
  {
    id: `${light}_${normal}_6f`,
    table: Light,
    difficulty: Normal,
    map: 6,
    mission: "F",
    energy: 8,
    characters: [],
  },
  {
    id: `${light}_${normal}_6g`,
    table: Light,
    difficulty: Normal,
    map: 6,
    mission: "G",
    energy: 8,
    characters: [],
  },
  {
    id: `${light}_${normal}_6h`,
    table: Light,
    difficulty: Normal,
    map: 6,
    mission: "H",
    energy: 8,
    characters: [],
  },
  {
    id: `${light}_${normal}_6i`,
    table: Light,
    difficulty: Normal,
    map: 6,
    mission: "I",
    energy: 8,
    characters: [],
  },
  {
    id: `${light}_${normal}_6j`,
    table: Light,
    difficulty: Normal,
    map: 6,
    mission: "J",
    energy: 8,
    characters: [],
  },
  {
    id: `${light}_${normal}_7a`,
    table: Light,
    difficulty: Normal,
    map: 7,
    mission: "A",
    energy: 10,
    characters: [],
  },
  {
    id: `${light}_${normal}_7b`,
    table: Light,
    difficulty: Normal,
    map: 7,
    mission: "B",
    energy: 10,
    characters: [],
  },
  {
    id: `${light}_${normal}_7c`,
    table: Light,
    difficulty: Normal,
    map: 7,
    mission: "C",
    energy: 10,
    characters: [],
  },
  {
    id: `${light}_${normal}_7d`,
    table: Light,
    difficulty: Normal,
    map: 7,
    mission: "D",
    energy: 10,
    characters: [],
  },
  {
    id: `${light}_${normal}_7e`,
    table: Light,
    difficulty: Normal,
    map: 7,
    mission: "E",
    energy: 10,
    characters: [],
  },
  {
    id: `${light}_${normal}_7f`,
    table: Light,
    difficulty: Normal,
    map: 7,
    mission: "F",
    energy: 10,
    characters: [],
  },
  {
    id: `${light}_${normal}_7g`,
    table: Light,
    difficulty: Normal,
    map: 7,
    mission: "G",
    energy: 10,
    characters: [],
  },
  {
    id: `${light}_${normal}_7h`,
    table: Light,
    difficulty: Normal,
    map: 7,
    mission: "H",
    energy: 10,
    characters: [],
  },
  {
    id: `${light}_${normal}_8a`,
    table: Light,
    difficulty: Normal,
    map: 8,
    mission: "A",
    energy: 10,
    characters: [],
  },
  {
    id: `${light}_${normal}_8b`,
    table: Light,
    difficulty: Normal,
    map: 8,
    mission: "B",
    energy: 10,
    characters: [],
  },
  {
    id: `${light}_${normal}_8c`,
    table: Light,
    difficulty: Normal,
    map: 8,
    mission: "C",
    energy: 10,
    characters: [],
  },
  {
    id: `${light}_${normal}_8d`,
    table: Light,
    difficulty: Normal,
    map: 8,
    mission: "D",
    energy: 10,
    characters: [],
  },
  {
    id: `${light}_${normal}_8e`,
    table: Light,
    difficulty: Normal,
    map: 8,
    mission: "E",
    energy: 10,
    characters: [],
  },
  {
    id: `${light}_${normal}_8f`,
    table: Light,
    difficulty: Normal,
    map: 8,
    mission: "F",
    energy: 10,
    characters: [],
  },
  {
    id: `${light}_${normal}_8g`,
    table: Light,
    difficulty: Normal,
    map: 8,
    mission: "G",
    energy: 10,
    characters: [],
  },
  {
    id: `${light}_${normal}_8h`,
    table: Light,
    difficulty: Normal,
    map: 8,
    mission: "H",
    energy: 10,
    characters: [],
  },
  {
    id: `${light}_${normal}_9a`,
    table: Light,
    difficulty: Normal,
    map: 9,
    mission: "A",
    energy: 10,
    characters: [],
  },
  {
    id: `${light}_${normal}_9b`,
    table: Light,
    difficulty: Normal,
    map: 9,
    mission: "B",
    energy: 10,
    characters: [],
  },
  {
    id: `${light}_${normal}_9c`,
    table: Light,
    difficulty: Normal,
    map: 9,
    mission: "C",
    energy: 10,
    characters: [],
  },
  {
    id: `${light}_${normal}_9d`,
    table: Light,
    difficulty: Normal,
    map: 9,
    mission: "D",
    energy: 10,
    characters: [],
  },
  {
    id: `${light}_${normal}_9e`,
    table: Light,
    difficulty: Normal,
    map: 9,
    mission: "E",
    energy: 10,
    characters: [],
  },
  {
    id: `${light}_${normal}_9f`,
    table: Light,
    difficulty: Normal,
    map: 9,
    mission: "F",
    energy: 10,
    characters: [],
  },
  {
    id: `${light}_${normal}_9g`,
    table: Light,
    difficulty: Normal,
    map: 9,
    mission: "G",
    energy: 10,
    characters: [],
  },
  {
    id: `${light}_${normal}_9h`,
    table: Light,
    difficulty: Normal,
    map: 9,
    mission: "H",
    energy: 10,
    characters: [],
  },
  {
    id: `${dark}_${normal}_1a`,
    table: Dark,
    difficulty: Normal,
    map: 1,
    mission: "A",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_1b`,
    table: Dark,
    difficulty: Normal,
    map: 1,
    mission: "B",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_1c`,
    table: Dark,
    difficulty: Normal,
    map: 1,
    mission: "C",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_1d`,
    table: Dark,
    difficulty: Normal,
    map: 1,
    mission: "D",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_1e`,
    table: Dark,
    difficulty: Normal,
    map: 1,
    mission: "E",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_1f`,
    table: Dark,
    difficulty: Normal,
    map: 1,
    mission: "F",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_2a`,
    table: Dark,
    difficulty: Normal,
    map: 2,
    mission: "A",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_2b`,
    table: Dark,
    difficulty: Normal,
    map: 2,
    mission: "B",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_2c`,
    table: Dark,
    difficulty: Normal,
    map: 2,
    mission: "C",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_2d`,
    table: Dark,
    difficulty: Normal,
    map: 2,
    mission: "D",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_2e`,
    table: Dark,
    difficulty: Normal,
    map: 2,
    mission: "E",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_2f`,
    table: Dark,
    difficulty: Normal,
    map: 2,
    mission: "F",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_2g`,
    table: Dark,
    difficulty: Normal,
    map: 2,
    mission: "G",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_2h`,
    table: Dark,
    difficulty: Normal,
    map: 2,
    mission: "H",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_2i`,
    table: Dark,
    difficulty: Normal,
    map: 2,
    mission: "I",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_3a`,
    table: Dark,
    difficulty: Normal,
    map: 3,
    mission: "A",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_3b`,
    table: Dark,
    difficulty: Normal,
    map: 3,
    mission: "B",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_3c`,
    table: Dark,
    difficulty: Normal,
    map: 3,
    mission: "C",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_3d`,
    table: Dark,
    difficulty: Normal,
    map: 3,
    mission: "D",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_3e`,
    table: Dark,
    difficulty: Normal,
    map: 3,
    mission: "E",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_3f`,
    table: Dark,
    difficulty: Normal,
    map: 3,
    mission: "F",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_3g`,
    table: Dark,
    difficulty: Normal,
    map: 3,
    mission: "G",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_3h`,
    table: Dark,
    difficulty: Normal,
    map: 3,
    mission: "H",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_3i`,
    table: Dark,
    difficulty: Normal,
    map: 3,
    mission: "I",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_4a`,
    table: Dark,
    difficulty: Normal,
    map: 4,
    mission: "A",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_4b`,
    table: Dark,
    difficulty: Normal,
    map: 4,
    mission: "B",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_4c`,
    table: Dark,
    difficulty: Normal,
    map: 4,
    mission: "C",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_4d`,
    table: Dark,
    difficulty: Normal,
    map: 4,
    mission: "D",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_4e`,
    table: Dark,
    difficulty: Normal,
    map: 4,
    mission: "E",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_4f`,
    table: Dark,
    difficulty: Normal,
    map: 4,
    mission: "F",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_4g`,
    table: Dark,
    difficulty: Normal,
    map: 4,
    mission: "G",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_4h`,
    table: Dark,
    difficulty: Normal,
    map: 4,
    mission: "H",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_4i`,
    table: Dark,
    difficulty: Normal,
    map: 4,
    mission: "I",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_4j`,
    table: Dark,
    difficulty: Normal,
    map: 4,
    mission: "J",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_4k`,
    table: Dark,
    difficulty: Normal,
    map: 4,
    mission: "K",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_4l`,
    table: Dark,
    difficulty: Normal,
    map: 4,
    mission: "L",
    energy: 6,
    characters: [],
  },
  {
    id: `${dark}_${normal}_5a`,
    table: Dark,
    difficulty: Normal,
    map: 5,
    mission: "A",
    energy: 8,
    characters: [],
  },
  {
    id: `${dark}_${normal}_5a`,
    table: Dark,
    difficulty: Normal,
    map: 5,
    mission: "A",
    energy: 8,
    characters: [],
  },
  {
    id: `${dark}_${normal}_5b`,
    table: Dark,
    difficulty: Normal,
    map: 5,
    mission: "B",
    energy: 8,
    characters: [],
  },
  {
    id: `${dark}_${normal}_5c`,
    table: Dark,
    difficulty: Normal,
    map: 5,
    mission: "C",
    energy: 8,
    characters: [],
  },
  {
    id: `${dark}_${normal}_5d`,
    table: Dark,
    difficulty: Normal,
    map: 5,
    mission: "D",
    energy: 8,
    characters: [],
  },
  {
    id: `${dark}_${normal}_5e`,
    table: Dark,
    difficulty: Normal,
    map: 5,
    mission: "E",
    energy: 8,
    characters: [],
  },
  {
    id: `${dark}_${normal}_5f`,
    table: Dark,
    difficulty: Normal,
    map: 5,
    mission: "F",
    energy: 8,
    characters: [],
  },
  {
    id: `${dark}_${normal}_5g`,
    table: Dark,
    difficulty: Normal,
    map: 5,
    mission: "G",
    energy: 8,
    characters: [],
  },
  {
    id: `${dark}_${normal}_5h`,
    table: Dark,
    difficulty: Normal,
    map: 5,
    mission: "H",
    energy: 8,
    characters: [],
  },
  {
    id: `${dark}_${normal}_5i`,
    table: Dark,
    difficulty: Normal,
    map: 5,
    mission: "I",
    energy: 8,
    characters: [],
  },
  {
    id: `${dark}_${normal}_5j`,
    table: Dark,
    difficulty: Normal,
    map: 5,
    mission: "J",
    energy: 8,
    characters: [],
  },
  {
    id: `${dark}_${normal}_5k`,
    table: Dark,
    difficulty: Normal,
    map: 5,
    mission: "K",
    energy: 8,
    characters: [],
  },
  {
    id: `${dark}_${normal}_5l`,
    table: Dark,
    difficulty: Normal,
    map: 5,
    mission: "L",
    energy: 8,
    characters: [],
  },
  {
    id: `${dark}_${normal}_6a`,
    table: Dark,
    difficulty: Normal,
    map: 6,
    mission: "A",
    energy: 8,
    characters: [],
  },
  {
    id: `${dark}_${normal}_6b`,
    table: Dark,
    difficulty: Normal,
    map: 6,
    mission: "B",
    energy: 8,
    characters: [],
  },
  {
    id: `${dark}_${normal}_6c`,
    table: Dark,
    difficulty: Normal,
    map: 6,
    mission: "C",
    energy: 8,
    characters: [],
  },
  {
    id: `${dark}_${normal}_6d`,
    table: Dark,
    difficulty: Normal,
    map: 6,
    mission: "D",
    energy: 8,
    characters: [],
  },
  {
    id: `${dark}_${normal}_6e`,
    table: Dark,
    difficulty: Normal,
    map: 6,
    mission: "E",
    energy: 8,
    characters: [],
  },
  {
    id: `${dark}_${normal}_6f`,
    table: Dark,
    difficulty: Normal,
    map: 6,
    mission: "F",
    energy: 8,
    characters: [],
  },
  {
    id: `${dark}_${normal}_6g`,
    table: Dark,
    difficulty: Normal,
    map: 6,
    mission: "G",
    energy: 8,
    characters: [],
  },
  {
    id: `${dark}_${normal}_6h`,
    table: Dark,
    difficulty: Normal,
    map: 6,
    mission: "H",
    energy: 8,
    characters: [],
  },
  {
    id: `${dark}_${normal}_6i`,
    table: Dark,
    difficulty: Normal,
    map: 6,
    mission: "I",
    energy: 8,
    characters: [],
  },
  {
    id: `${dark}_${normal}_6j`,
    table: Dark,
    difficulty: Normal,
    map: 6,
    mission: "J",
    energy: 8,
    characters: [],
  },
  {
    id: `${dark}_${normal}_7a`,
    table: Dark,
    difficulty: Normal,
    map: 7,
    mission: "A",
    energy: 10,
    characters: [],
  },
  {
    id: `${dark}_${normal}_7b`,
    table: Dark,
    difficulty: Normal,
    map: 7,
    mission: "B",
    energy: 10,
    characters: [],
  },
  {
    id: `${dark}_${normal}_7c`,
    table: Dark,
    difficulty: Normal,
    map: 7,
    mission: "C",
    energy: 10,
    characters: [],
  },
  {
    id: `${dark}_${normal}_7d`,
    table: Dark,
    difficulty: Normal,
    map: 7,
    mission: "D",
    energy: 10,
    characters: [],
  },
  {
    id: `${dark}_${normal}_7e`,
    table: Dark,
    difficulty: Normal,
    map: 7,
    mission: "E",
    energy: 10,
    characters: [],
  },
  {
    id: `${dark}_${normal}_7f`,
    table: Dark,
    difficulty: Normal,
    map: 7,
    mission: "F",
    energy: 10,
    characters: [],
  },
  {
    id: `${dark}_${normal}_7g`,
    table: Dark,
    difficulty: Normal,
    map: 7,
    mission: "G",
    energy: 10,
    characters: [],
  },
  {
    id: `${dark}_${normal}_7h`,
    table: Dark,
    difficulty: Normal,
    map: 7,
    mission: "H",
    energy: 10,
    characters: [],
  },
  {
    id: `${dark}_${normal}_8a`,
    table: Dark,
    difficulty: Normal,
    map: 8,
    mission: "A",
    energy: 10,
    characters: [],
  },
  {
    id: `${dark}_${normal}_8b`,
    table: Dark,
    difficulty: Normal,
    map: 8,
    mission: "B",
    energy: 10,
    characters: [],
  },
  {
    id: `${dark}_${normal}_8c`,
    table: Dark,
    difficulty: Normal,
    map: 8,
    mission: "C",
    energy: 10,
    characters: [],
  },
  {
    id: `${dark}_${normal}_8d`,
    table: Dark,
    difficulty: Normal,
    map: 8,
    mission: "D",
    energy: 10,
    characters: [],
  },
  {
    id: `${dark}_${normal}_8e`,
    table: Dark,
    difficulty: Normal,
    map: 8,
    mission: "E",
    energy: 10,
    characters: [],
  },
  {
    id: `${dark}_${normal}_8f`,
    table: Dark,
    difficulty: Normal,
    map: 8,
    mission: "F",
    energy: 10,
    characters: [],
  },
  {
    id: `${dark}_${normal}_8g`,
    table: Dark,
    difficulty: Normal,
    map: 8,
    mission: "G",
    energy: 10,
    characters: [],
  },
  {
    id: `${dark}_${normal}_8h`,
    table: Dark,
    difficulty: Normal,
    map: 8,
    mission: "H",
    energy: 10,
    characters: [],
  },
  {
    id: `${dark}_${normal}_9a`,
    table: Dark,
    difficulty: Normal,
    map: 9,
    mission: "A",
    energy: 10,
    characters: [],
  },
  {
    id: `${dark}_${normal}_9b`,
    table: Dark,
    difficulty: Normal,
    map: 9,
    mission: "B",
    energy: 10,
    characters: [],
  },
  {
    id: `${dark}_${normal}_9c`,
    table: Dark,
    difficulty: Normal,
    map: 9,
    mission: "C",
    energy: 10,
    characters: [],
  },
  {
    id: `${dark}_${normal}_9d`,
    table: Dark,
    difficulty: Normal,
    map: 9,
    mission: "D",
    energy: 10,
    characters: [],
  },
  {
    id: `${dark}_${normal}_9e`,
    table: Dark,
    difficulty: Normal,
    map: 9,
    mission: "E",
    energy: 10,
    characters: [],
  },
  {
    id: `${dark}_${normal}_9f`,
    table: Dark,
    difficulty: Normal,
    map: 9,
    mission: "F",
    energy: 10,
    characters: [],
  },
  {
    id: `${dark}_${normal}_9g`,
    table: Dark,
    difficulty: Normal,
    map: 9,
    mission: "G",
    energy: 10,
    characters: [],
  },
  {
    id: `${dark}_${normal}_9h`,
    table: Dark,
    difficulty: Normal,
    map: 9,
    mission: "H",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_1a`,
    table: Fleet,
    difficulty: Normal,
    map: 1,
    mission: "A",
    energy: 8,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_1b`,
    table: Fleet,
    difficulty: Normal,
    map: 1,
    mission: "B",
    energy: 8,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_1c`,
    table: Fleet,
    difficulty: Normal,
    map: 1,
    mission: "C",
    energy: 8,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_1d`,
    table: Fleet,
    difficulty: Normal,
    map: 1,
    mission: "D",
    energy: 8,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_1e`,
    table: Fleet,
    difficulty: Normal,
    map: 1,
    mission: "E",
    energy: 8,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_1f`,
    table: Fleet,
    difficulty: Normal,
    map: 1,
    mission: "F",
    energy: 8,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_1g`,
    table: Fleet,
    difficulty: Normal,
    map: 1,
    mission: "G",
    energy: 8,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_2a`,
    table: Fleet,
    difficulty: Normal,
    map: 2,
    mission: "A",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_2b`,
    table: Fleet,
    difficulty: Normal,
    map: 2,
    mission: "B",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_2c`,
    table: Fleet,
    difficulty: Normal,
    map: 2,
    mission: "C",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_2d`,
    table: Fleet,
    difficulty: Normal,
    map: 2,
    mission: "D",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_2e`,
    table: Fleet,
    difficulty: Normal,
    map: 2,
    mission: "E",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_2f`,
    table: Fleet,
    difficulty: Normal,
    map: 2,
    mission: "F",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_2g`,
    table: Fleet,
    difficulty: Normal,
    map: 2,
    mission: "G",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_3a`,
    table: Fleet,
    difficulty: Normal,
    map: 3,
    mission: "A",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_3b`,
    table: Fleet,
    difficulty: Normal,
    map: 3,
    mission: "B",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_3c`,
    table: Fleet,
    difficulty: Normal,
    map: 3,
    mission: "C",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_3d`,
    table: Fleet,
    difficulty: Normal,
    map: 3,
    mission: "D",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_3e`,
    table: Fleet,
    difficulty: Normal,
    map: 3,
    mission: "E",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_3f`,
    table: Fleet,
    difficulty: Normal,
    map: 3,
    mission: "F",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_3g`,
    table: Fleet,
    difficulty: Normal,
    map: 3,
    mission: "G",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_4a`,
    table: Fleet,
    difficulty: Normal,
    map: 4,
    mission: "A",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_4b`,
    table: Fleet,
    difficulty: Normal,
    map: 4,
    mission: "B",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_4c`,
    table: Fleet,
    difficulty: Normal,
    map: 4,
    mission: "C",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_4d`,
    table: Fleet,
    difficulty: Normal,
    map: 4,
    mission: "D",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_4e`,
    table: Fleet,
    difficulty: Normal,
    map: 4,
    mission: "E",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_4f`,
    table: Fleet,
    difficulty: Normal,
    map: 4,
    mission: "F",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_4g`,
    table: Fleet,
    difficulty: Normal,
    map: 4,
    mission: "G",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_5a`,
    table: Fleet,
    difficulty: Normal,
    map: 5,
    mission: "A",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_5b`,
    table: Fleet,
    difficulty: Normal,
    map: 5,
    mission: "B",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_5c`,
    table: Fleet,
    difficulty: Normal,
    map: 5,
    mission: "C",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_5d`,
    table: Fleet,
    difficulty: Normal,
    map: 5,
    mission: "D",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_5e`,
    table: Fleet,
    difficulty: Normal,
    map: 5,
    mission: "E",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_5f`,
    table: Fleet,
    difficulty: Normal,
    map: 5,
    mission: "F",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_5g`,
    table: Fleet,
    difficulty: Normal,
    map: 5,
    mission: "G",
    energy: 10,
    characters: [],
  },
  {
    id: `${fleet}_${normal}_5h`,
    table: Fleet,
    difficulty: Normal,
    map: 5,
    mission: "H",
    energy: 10,
    characters: [],
  },
];