const ships = [
  {
    name: "Ahsoka Tano's Jedi Starfighter",
    id: "JEDISTARFIGHTERAHSOKATANO",
    url: "http://swgoh.gg/ships/ahsoka-tanos-jedi-starfighter/",
    image: "https://game-assets.swgoh.gg/tex.charui_jedi_fighter_ahsoka.png",
    description:
      "Versatile Jedi Attacker that uses dispels and buffs to adapt to the battle",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Attacker", "Galactic Republic", "Jedi"],
    ability_classes: [
      "Dispel",
      "Gain Turn Meter",
      "Offense Up",
      "Reset Cooldown",
    ],
    role: "Attacker",
    capital_ship: false,
    activate_shard_count: 10,
  },
  {
    name: "Anakin's Eta-2 Starfighter",
    id: "JEDISTARFIGHTERANAKIN",
    url: "http://swgoh.gg/ships/anakins-eta-2-starfighter/",
    image: "https://game-assets.swgoh.gg/tex.charui_jedi_fighter_anakin.png",
    description:
      "Aggressive Jedi Attacker that bolsters Offense and retaliates when allies are in trouble",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Attacker", "Galactic Republic", "Jedi"],
    ability_classes: [
      "AoE",
      "Buff Immunity",
      "Expose",
      "Healing Immunity",
      "Offense Up",
    ],
    role: "Attacker",
    capital_ship: false,
    activate_shard_count: 25,
  },
  {
    name: "B-28 Extinction-class Bomber",
    id: "SITHBOMBER",
    aliases: ["Sith Marauder"],
    url: "http://swgoh.gg/ships/b-28-extinction-class-bomber/",
    image:
      "https://game-assets.swgoh.gg/tex.charui_b28extinctionclassbomber.png",
    description:
      "Aggressive Sith Tank with a passive Taunt and self-preservation tactics",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Sith", "Sith Empire", "Tank"],
    ability_classes: ["AoE", "Daze", "Defense Up", "Dispel", "Taunt"],
    role: "Tank",
    capital_ship: false,
    activate_shard_count: 25,
  },
  {
    name: "Biggs Darklighter's X-wing",
    id: "XWINGRED3",
    aliases: ["xwing", "rebel xwing", "rebel x-wing"],
    url: "http://swgoh.gg/ships/biggs-darklighters-x-wing/",
    image: "https://game-assets.swgoh.gg/tex.charui_xwing_red3.png",
    description:
      "Heroic Rebel Tank that can exploit Target Lock for Taunts and Assists",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Rebel", "Tank"],
    ability_classes: ["Taunt"],
    role: "Tank",
    capital_ship: false,
    activate_shard_count: 10,
  },
  {
    name: "Bistan's U-wing",
    id: "UWINGSCARIF",
    aliases: ["uwing", "rebel uwing", "rebel u-wing"],
    url: "http://swgoh.gg/ships/bistans-u-wing/",
    image: "https://game-assets.swgoh.gg/tex.charui_uwing.png",
    description:
      "Elusive Rebel Support that boosts ally Turn Meter while using Stealth and Target Lock",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Rebel", "Rogue One", "Support"],
    ability_classes: ["Assist", "Gain Turn Meter", "Stealth", "Tenacity Down"],
    role: "Support",
    capital_ship: false,
    activate_shard_count: 50,
  },
  {
    name: "BTL-B Y-wing Starfighter",
    id: "YWINGCLONEWARS",
    aliases: [
      "ywing",
      "crewless",
      "republic ywing",
      "republic y-wing",
      "gr ywing",
      "gr y-wing",
      "why wing",
    ],
    url: "http://swgoh.gg/ships/btl-b-y-wing-starfighter/",
    image: "https://game-assets.swgoh.gg/tex.charui_ywing_btlb.png",
    description:
      "Galactic Republic Tank that can withstand significant damage and Taunts when its allies are in need",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Galactic Republic", "Tank"],
    ability_classes: ["Counter", "Dispel", "Taunt"],
    role: "Tank",
    capital_ship: false,
    activate_shard_count: 25,
  },
  {
    name: "Cassian's U-wing",
    id: "UWINGROGUEONE",
    aliases: [
      "uwing",
      "rebel uwing",
      "rebel u-wing",
      "cassian uwing",
      "cassian's uwing",
    ],
    url: "http://swgoh.gg/ships/cassians-u-wing/",
    image: "https://game-assets.swgoh.gg/tex.charui_uwing_hero.png",
    description:
      "Evasive Rebel Support ship that turns the tide of battle with Stealth and Turn Meter manipulation",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Rebel", "Rogue One", "Support"],
    ability_classes: [
      "AoE",
      "Counter",
      "Defense Down",
      "Dispel",
      "Gain Turn Meter",
      "Offense Down",
    ],
    role: "Support",
    capital_ship: false,
    activate_shard_count: 80,
  },
  {
    name: "Chimaera",
    id: "CAPITALCHIMAERA",
    aliases: ["thrawn"],
    url: "http://swgoh.gg/ships/chimaera/",
    image: "https://game-assets.swgoh.gg/tex.charui_chimaera.png",
    description:
      "Tactical Empire Capital Ship that shuts down enemy Capital Ships and manipulates the flow of battle",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Capital Ship", "Empire"],
    ability_classes: [
      "Ability Block",
      "AoE",
      "Assist",
      "Defense Down",
      "Defense Up",
      "Foresight",
      "Heal",
      "Offense Down",
      "Offense Up",
      "Remove Turn Meter",
      "Speed Down",
    ],
    role: "Capital Ship",
    capital_ship: true,
    activate_shard_count: 145,
    statMultipliers: {
      speed: 0.00299401,
      health: 0,
      protection: 0,
      physicalDamage: 0.206859,
      critRating: 0,
      specialDamage: 1.0587915,
      specialCrit: 0,
      potency: 0.00002268,
      tenacity: 0.00002268,
    },
  },
  {
    name: "Clone Sergeant's ARC-170",
    id: "ARC170CLONESERGEANT",
    url: "http://swgoh.gg/ships/clone-sergeants-arc-170/",
    image: "https://game-assets.swgoh.gg/tex.charui_arc170.png",
    description:
      "Reliable Clone Tank that both inflicts and exploits Target Lock",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Clone Trooper", "Galactic Republic", "Tank"],
    ability_classes: ["Defense Up", "Taunt"],
    role: "Tank",
    capital_ship: false,
    activate_shard_count: 10,
  },
  {
    name: "Ebon Hawk",
    id: "EBONHAWK",
    aliases: ["T3M4", "carth"],
    url: "http://swgoh.gg/ships/ebon-hawk/",
    image: "https://game-assets.swgoh.gg/tex.charui_ebonhawk.png",
    description:
      "Durable Old Republic Support that dispels enemies and prevents Target Lock",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Cargo Ship", "Old Republic", "Support"],
    ability_classes: [
      "AoE",
      "Bonus Attack",
      "Dispel",
      "Evasion Down",
      "Foresight",
      "Gain Turn Meter",
    ],
    role: "Support",
    capital_ship: false,
    activate_shard_count: 80,
  },
  {
    name: "Emperor's Shuttle",
    id: "EMPERORSSHUTTLE",
    aliases: ["royal guard"],
    url: "http://swgoh.gg/ships/emperors-shuttle/",
    image: "https://game-assets.swgoh.gg/tex.charui_imperialshuttle.png",
    description:
      "Versatile Support that boosts Empire and Sith survivability while debuffing enemies",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Empire", "Sith", "Support"],
    ability_classes: ["Dispel", "Offense Up", "Taunt", "Tenacity Down"],
    role: "Support",
    capital_ship: false,
    activate_shard_count: 80,
  },
  {
    name: "Endurance",
    id: "CAPITALJEDICRUISER",
    aliases: ["mace"],
    url: "http://swgoh.gg/ships/endurance/",
    image: "https://game-assets.swgoh.gg/tex.charui_venator.png",
    description:
      "Defensive Jedi Capital Ship that uses Valor to gain a huge Speed advantage",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Capital Ship", "Galactic Republic", "Jedi"],
    ability_classes: ["Taunt"],
    role: "Capital Ship",
    capital_ship: true,
    activate_shard_count: 10,
    statMultipliers: {
      speed: 0.00319857,
      health: 0,
      protection: 0,
      physicalDamage: 0.35560572,
      critRating: 0,
      specialDamage: 0,
      specialCrit: 0,
      potency: 0.00002351,
      tenacity: 0.00002351,
    },
  },
  {
    name: "Executor",
    id: "CAPITALEXECUTOR",
    aliases: ["piett", "bh capital"],
    url: "http://swgoh.gg/ships/executor/",
    image: "https://game-assets.swgoh.gg/tex.charui_executor.png",
    description: "Empire Capital Ship with strong Bounty Hunter synergy.",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Capital Ship", "Empire"],
    ability_classes: [
      "AoE",
      "Assist",
      "Dispel",
      "Expose",
      "Foresight",
      "Stealth",
      "Stun",
      "Taunt",
      "Tenacity Up",
    ],
    role: "Capital Ship",
    capital_ship: true,
    activate_shard_count: 80,
  },
  {
    name: "Executrix",
    id: "CAPITALSTARDESTROYER",
    aliases: ["tarkin"],
    url: "http://swgoh.gg/ships/executrix/",
    image: "https://game-assets.swgoh.gg/tex.charui_stardestroyer.png",
    description: "Aggressive Empire Capital Ship that crushes debuffed enemies",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Capital Ship", "Empire"],
    ability_classes: [
      "Ability Block",
      "AoE",
      "Expose",
      "Gain Turn Meter",
      "Offense Up",
      "Stun",
      "Tenacity Down",
    ],
    role: "Capital Ship",
    capital_ship: true,
    activate_shard_count: 10,
  },
  {
    name: "Finalizer",
    id: "CAPITALFINALIZER",
    aliases: ["hux"],
    url: "http://swgoh.gg/ships/finalizer/",
    image: "https://game-assets.swgoh.gg/tex.charui_finalizer.png",
    description:
      "First Order Capital Ship that enables the First Order fleet to have an early game advantage and relentlessly pursue enemies",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Capital Ship", "First Order"],
    ability_classes: [
      "AoE",
      "Assist",
      "Dispel",
      "Gain Turn Meter",
      "Offense Down",
      "Offense Up",
    ],
    role: "Capital Ship",
    capital_ship: true,
    activate_shard_count: 80,
  },
  {
    name: "First Order SF TIE Fighter",
    id: "TIEFIGHTERFOSF",
    aliases: ["fo sf tie", "fosf tie"],
    url: "http://swgoh.gg/ships/first-order-sf-tie-fighter/",
    image: "https://game-assets.swgoh.gg/tex.charui_fosf_tie_fighter.png",
    description:
      "Superior First Order Attacker that has multiple offensive capabilities and inflicts multiple debuffs",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Attacker", "First Order"],
    ability_classes: ["AoE", "DoT"],
    role: "Attacker",
    capital_ship: false,
    activate_shard_count: 10,
  },
  {
    name: "First Order TIE Fighter",
    id: "TIEFIGHTERFIRSTORDER",
    aliases: ["fo tie fighter"],
    url: "http://swgoh.gg/ships/first-order-tie-fighter/",
    image: "https://game-assets.swgoh.gg/tex.charui_firstorder_tiefighter.png",
    description:
      "Aggressive First Order Attacker with reliable Target Lock and rapid-fire Special ability",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Attacker", "First Order"],
    ability_classes: ["Bonus Attack", "Gain Turn Meter"],
    role: "Attacker",
    capital_ship: false,
    activate_shard_count: 10,
  },
  {
    name: "Gauntlet Starfighter",
    id: "GAUNTLETSTARFIGHTER",
    aliases: [
      "GARSAXON",
      "gar saxon",
      "IMPERIALSUPERCOMMANDO",
      "imperial",
      "empire",
    ],
    url: "http://swgoh.gg/ships/gauntlet-starfighter/",
    image: "https://game-assets.swgoh.gg/tex.charui_gauntlet.png",
    description:
      "Reliable Empire Support that dispels ally debuffs and prevents enemy buffs",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Empire", "Support"],
    ability_classes: ["Heal"],
    role: "Support",
    capital_ship: false,
    activate_shard_count: 25,
  },
  {
    name: "Geonosian Soldier's Starfighter",
    id: "GEONOSIANSTARFIGHTER2",
    aliases: ["geo ship", "geo soldier"],
    url: "http://swgoh.gg/ships/geonosian-soldiers-starfighter/",
    image:
      "https://game-assets.swgoh.gg/tex.charui_geonosis_fighter_soldier.png",
    description:
      "Aggressive Separatist Attacker that can Assist allies automatically",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Attacker", "Geonosian", "Separatist"],
    ability_classes: [
      "Assist",
      "Gain Turn Meter",
      "Offense Up",
      "Remove Turn Meter",
    ],
    role: "Attacker",
    capital_ship: false,
    activate_shard_count: 10,
  },
  {
    name: "Geonosian Spy's Starfighter",
    id: "GEONOSIANSTARFIGHTER3",
    aliases: ["geo ship", "geo spy"],
    url: "http://swgoh.gg/ships/geonosian-spys-starfighter/",
    image: "https://game-assets.swgoh.gg/tex.charui_geonosis_fighter_spy.png",
    description:
      "Elusive Separatist Attacker that uses Stealth for both offense and defense",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Attacker", "Geonosian", "Separatist"],
    ability_classes: ["Stealth", "Taunt"],
    role: "Attacker",
    capital_ship: false,
    activate_shard_count: 10,
  },
  {
    name: "Ghost",
    id: "GHOST",
    aliases: ["kanan", "hera", "zeb"],
    url: "http://swgoh.gg/ships/ghost/",
    image: "https://game-assets.swgoh.gg/tex.charui_ghost.png",
    description:
      "Elusive Rebel attacker that reduces enemy Potency and wreaks havok with Rebel allies",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Attacker", "Cargo Ship", "Phoenix", "Rebel"],
    ability_classes: ["AoE", "Speed Down", "Stealth"],
    role: "Attacker",
    capital_ship: false,
    activate_shard_count: 25,
  },
  {
    name: "Han's Millennium Falcon",
    id: "MILLENNIUMFALCON",
    aliases: ["milf", "chewy", "chewbacca"],
    url: "http://swgoh.gg/ships/hans-millennium-falcon/",
    image: "https://game-assets.swgoh.gg/tex.charui_mfalcon.png",
    description:
      "Highly-modified Rebel Attacker that specializes in assists and shows up at just the right time",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Attacker", "Cargo Ship", "Rebel", "Scoundrel"],
    ability_classes: ["Assist", "Dispel", "Foresight"],
    role: "Attacker",
    capital_ship: false,
    activate_shard_count: 145,
  },
  {
    name: "Home One",
    id: "CAPITALMONCALAMARICRUISER",
    aliases: ["ackbar", "h1", "home1", "homeone"],
    url: "http://swgoh.gg/ships/home-one/",
    image:
      "https://game-assets.swgoh.gg/tex.charui_moncalamarilibertycruiser.png",
    description:
      "Versatile Rebel Capital Ship that uses Advantage and bonus attacks to turn the tide",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Capital Ship", "Rebel"],
    ability_classes: [
      "Advantage",
      "AoE",
      "Assist",
      "Dispel",
      "Gain Turn Meter",
      "Reset Cooldown",
    ],
    role: "Capital Ship",
    capital_ship: true,
    activate_shard_count: 10,
  },
  {
    name: "Hound's Tooth",
    id: "HOUNDSTOOTH",
    aliases: ["ht", "bossk"],
    url: "http://swgoh.gg/ships/hounds-tooth/",
    image: "https://game-assets.swgoh.gg/tex.charui_houndstooth.png",
    description: "Sustainable Bounty Hunter Tank that debilitates enemies",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Bounty Hunter", "Cargo Ship", "Scoundrel", "Tank"],
    ability_classes: ["Counter", "Dispel", "Taunt"],
    role: "Tank",
    capital_ship: false,
    activate_shard_count: 25,
  },
  {
    name: "Hyena Bomber",
    id: "HYENABOMBER",
    aliases: ["crewless"],
    url: "http://swgoh.gg/ships/hyena-bomber/",
    image: "https://game-assets.swgoh.gg/tex.charui_hyenabomber.png",
    description:
      "Robust Separatist Tank that inflicts Buzz Droids and protects allies",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Droid", "Separatist", "Tank"],
    ability_classes: ["AoE", "Dispel", "Taunt"],
    role: "Tank",
    capital_ship: false,
    activate_shard_count: 80,
  },
  {
    name: "IG-2000",
    id: "IG2000",
    aliases: ["ig88", "ig-88"],
    url: "http://swgoh.gg/ships/ig-2000/",
    image: "https://game-assets.swgoh.gg/tex.charui_ig2000.png",
    description:
      "Aggressive Bounty Hunter Attacker that deals massive damage to Breached enemies",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Attacker", "Bounty Hunter", "Droid", "Scoundrel"],
    ability_classes: ["AoE", "Bonus Attack", "Offense Up", "Stun"],
    role: "Attacker",
    capital_ship: false,
    activate_shard_count: 25,
  },
  {
    name: "Imperial TIE Bomber",
    id: "TIEBOMBERIMPERIAL",
    aliases: ["crewless"],
    url: "http://swgoh.gg/ships/imperial-tie-bomber/",
    image: "https://game-assets.swgoh.gg/tex.charui_tiebomber.png",
    description:
      "Debilitating Empire Tank that inflicts Burning, cripples enemies' Offense, and provides heavy defensive capability.",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Empire", "Tank"],
    ability_classes: ["AoE", "Assist", "Dispel", "Taunt"],
    role: "Tank",
    capital_ship: false,
    activate_shard_count: 80,
  },
  {
    name: "Imperial TIE Fighter",
    id: "TIEFIGHTERIMPERIAL",
    aliases: ["empire tie"],
    url: "http://swgoh.gg/ships/imperial-tie-fighter/",
    image: "https://game-assets.swgoh.gg/tex.charui_tiefighter.png",
    description:
      "Evasive Empire Attacker that both inflicts and exploits Target Lock",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Attacker", "Empire"],
    ability_classes: ["Buff Immunity", "Foresight", "Remove Turn Meter"],
    role: "Attacker",
    capital_ship: false,
    activate_shard_count: 10,
  },
  {
    name: "Jedi Consular's Starfighter",
    id: "JEDISTARFIGHTERCONSULAR",
    url: "http://swgoh.gg/ships/jedi-consulars-starfighter/",
    image: "https://game-assets.swgoh.gg/tex.charui_jedi_fighter.png",
    description:
      "Defensive Jedi Support that can rapidly restore ally Protection",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Galactic Republic", "Jedi", "Support"],
    ability_classes: ["Assist", "Defense Up", "Heal"],
    role: "Support",
    capital_ship: false,
    activate_shard_count: 10,
  },
  {
    name: "Kylo Ren's Command Shuttle",
    id: "COMMANDSHUTTLE",
    aliases: ["kylo", "phasma"],
    url: "http://swgoh.gg/ships/kylo-rens-command-shuttle/",
    image: "https://game-assets.swgoh.gg/tex.charui_upsilon_shuttle_kylo.png",
    description:
      "Durable First Order Support with unparalleled ability to manipulate allied Turn Meter",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["First Order", "Support"],
    ability_classes: [
      "Ability Block",
      "Dispel",
      "Gain Turn Meter",
      "Healing Immunity",
      "Remove Turn Meter",
    ],
    role: "Support",
    capital_ship: false,
    activate_shard_count: 80,
  },
  {
    name: "Lando's Millennium Falcon",
    id: "MILLENNIUMFALCONPRISTINE",
    url: "http://swgoh.gg/ships/landos-millennium-falcon/",
    image: "https://game-assets.swgoh.gg/tex.charui_mil_fal_pristine.png",
    description:
      "Devastating Scoundrel attacker that becomes more threatening after each ally reinforcement",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Attacker", "Cargo Ship", "Scoundrel"],
    ability_classes: ["Counter", "Dispel"],
    role: "Attacker",
    capital_ship: false,
    activate_shard_count: 25,
  },
  {
    name: "Malevolence",
    id: "CAPITALMALEVOLENCE",
    aliases: ["grievous", "gg"],
    url: "http://swgoh.gg/ships/malevolence/",
    image: "https://game-assets.swgoh.gg/tex.charui_malevolence.png",
    description:
      "Separatist Capital Ship that powers up both Separatists and Droids and has the means to shut down entire enemy fleets.",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Capital Ship", "Droid", "Separatist"],
    ability_classes: [
      "AoE",
      "Assist",
      "Dispel",
      "Gain Turn Meter",
      "Offense Down",
      "Remove Turn Meter",
      "Stun",
    ],
    role: "Capital Ship",
    capital_ship: true,
    activate_shard_count: 145,
  },
  {
    name: "Negotiator",
    id: "CAPITALNEGOTIATOR",
    aliases: ["gk", "kenobi", "general kenobi"],
    url: "http://swgoh.gg/ships/negotiator/",
    image: "https://game-assets.swgoh.gg/tex.charui_negotiator.png",
    description:
      "Offensive Jedi Capital Ship that uses Valor to bolster ally attacks and increase its Speed",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Capital Ship", "Galactic Republic", "Jedi"],
    ability_classes: [
      "AoE",
      "Assist",
      "Daze",
      "Dispel",
      "Gain Turn Meter",
      "Offense Down",
      "Offense Up",
      "Stealth",
    ],
    role: "Capital Ship",
    capital_ship: true,
    activate_shard_count: 145,
  },
  {
    name: "Phantom II",
    id: "PHANTOM2",
    aliases: ["sabine", "ezra", "chopper"],
    url: "http://swgoh.gg/ships/phantom-ii/",
    image: "https://game-assets.swgoh.gg/tex.charui_phantom2.png",
    description:
      "Evasive Rebel attacker that provides as a decoy for the Ghost while applying buffs to allies",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Attacker", "Cargo Ship", "Phoenix", "Rebel"],
    ability_classes: [
      "Advantage",
      "Dispel",
      "Foresight",
      "Offense Up",
      "Stealth",
      "Taunt",
    ],
    role: "Attacker",
    capital_ship: false,
    activate_shard_count: 25,
  },
  {
    name: "Plo Koon's Jedi Starfighter",
    id: "BLADEOFDORIN",
    url: "http://swgoh.gg/ships/plo-koons-jedi-starfighter/",
    image:
      "https://game-assets.swgoh.gg/tex.charui_jedi_fighter_bladeofdorin.png",
    description:
      "Versatile Jedi Support with powerful Republic buffs and a targeted ally Taunt",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Galactic Republic", "Jedi", "Support"],
    ability_classes: ["Dispel", "Taunt"],
    role: "Support",
    capital_ship: false,
    activate_shard_count: 25,
  },
  {
    name: "Poe Dameron's X-wing",
    id: "XWINGBLACKONE",
    aliases: [
      "x wing",
      "poe's xwing",
      "poes xwing",
      "poe's x-wing",
      "resistance xwing",
      "resistance x wing",
    ],
    url: "http://swgoh.gg/ships/poe-damerons-x-wing/",
    image: "https://game-assets.swgoh.gg/tex.charui_xwing_blackone.png",
    description:
      "Heroic Resistance Attacker that can exploit Turn Meter and punish enemies without Protection",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Attacker", "Resistance"],
    ability_classes: [
      "Daze",
      "Dispel",
      "Foresight",
      "Gain Turn Meter",
      "Offense Up",
    ],
    role: "Attacker",
    capital_ship: false,
    activate_shard_count: 50,
  },
  {
    name: "Raddus",
    id: "CAPITALRADDUS",
    aliases: ["raddus ship", "holdo"],
    url: "http://swgoh.gg/ships/raddus/",
    image: "https://game-assets.swgoh.gg/tex.charui_raddus.png",
    description:
      "Supportive Resistance Capital Ship that will do whatever is necessary to protect the fleet",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Capital Ship", "Resistance"],
    ability_classes: [
      "AoE",
      "Assist",
      "Buff Immunity",
      "Dispel",
      "Expose",
      "Foresight",
      "Gain Turn Meter",
      "Healing Immunity",
      "Tenacity Up",
    ],
    role: "Capital Ship",
    capital_ship: true,
    activate_shard_count: 80,
  },
  {
    name: "Razor Crest",
    id: "RAZORCREST",
    aliases: ["rc", "bam", "mando", "mandalorian"],
    url: "http://swgoh.gg/ships/razor-crest/",
    image: "https://game-assets.swgoh.gg/tex.charui_razorcrest.png",
    description: "Tenacious Bounty Hunter attacker with Breach synergy.",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Attacker", "Bounty Hunter", "Cargo Ship", "Scoundrel"],
    ability_classes: [
      "Ability Block",
      "Assist",
      "Buff Immunity",
      "Dispel",
      "Stealth",
      "Taunt",
    ],
    role: "Attacker",
    capital_ship: false,
    activate_shard_count: 145,
  },
  {
    name: "Rebel Y-wing",
    id: "YWINGREBEL",
    aliases: ["y wing", "crewless", "rebel ywing"],
    url: "http://swgoh.gg/ships/rebel-y-wing/",
    image: "https://game-assets.swgoh.gg/tex.charui_ywing.png",
    description: "Sturdy Rebel Tank that can disable enemy Protection",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Rebel", "Tank"],
    ability_classes: ["Assist", "Dispel", "Taunt"],
    role: "Tank",
    capital_ship: false,
    activate_shard_count: 80,
  },
  {
    name: "Resistance X-wing",
    id: "XWINGRESISTANCE",
    aliases: ["resistance xwing", "xwing", "x wing"],
    url: "http://swgoh.gg/ships/resistance-x-wing/",
    image: "https://game-assets.swgoh.gg/tex.charui_xwing_resistance.png",
    description:
      "Aggressive Resistance Support that shuts down enemies with Expose, Target Lock, and Daze",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Resistance", "Support"],
    ability_classes: [
      "Assist",
      "Daze",
      "Dispel",
      "Expose",
      "Remove Turn Meter",
    ],
    role: "Support",
    capital_ship: false,
    activate_shard_count: 10,
  },
  {
    name: "Rex's ARC-170",
    id: "ARC170REX",
    url: "http://swgoh.gg/ships/rexs-arc-170/",
    image: "https://game-assets.swgoh.gg/tex.charui_arc170_02.png",
    description:
      "Defensive Clone Tank that can inflict Target Lock and boost ally Protection and Tenacity",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Clone Trooper", "Galactic Republic", "Tank"],
    ability_classes: ["Remove Turn Meter"],
    role: "Tank",
    capital_ship: false,
    activate_shard_count: 50,
  },
  {
    name: "Rey's Millennium Falcon",
    id: "MILLENNIUMFALCONEP7",
    url: "http://swgoh.gg/ships/reys-millennium-falcon/",
    image: "https://game-assets.swgoh.gg/tex.charui_mfalcon_ep7.png",
    description:
      "Daring Resistance freighter that can turn the tide by sacrificing buffs",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Attacker", "Cargo Ship", "Resistance"],
    ability_classes: ["Counter", "Gain Turn Meter"],
    role: "Attacker",
    capital_ship: false,
    activate_shard_count: 80,
  },
  {
    name: "Scimitar",
    aliases: ["maul", "maul's ship"],
    id: "SITHINFILTRATOR",
    url: "http://swgoh.gg/ships/scimitar/",
    image: "https://game-assets.swgoh.gg/tex.charui_sithinfiltrator.png",
    description:
      "Deadly Sith Support that can Stealth allies to set up devastating attacks",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Sith", "Support"],
    ability_classes: ["Remove Turn Meter", "Stealth"],
    role: "Support",
    capital_ship: false,
    activate_shard_count: 50,
  },
  {
    name: "Sith Fighter",
    id: "SITHFIGHTER",
    aliases: ["SITHASSASSIN", "assassin"],
    url: "http://swgoh.gg/ships/sith-fighter/",
    image: "https://game-assets.swgoh.gg/tex.charui_sithfighter.png",
    description: "Agile Sith Attacker that bypasses enemy defenses",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Attacker", "Sith", "Sith Empire"],
    ability_classes: ["Foresight", "Gain Turn Meter", "Healing Immunity"],
    role: "Attacker",
    capital_ship: false,
    activate_shard_count: 25,
  },
  {
    name: "Slave I",
    id: "SLAVE1",
    aliases: ["boba", "fett", "boba's ship"],
    url: "http://swgoh.gg/ships/slave-i/",
    image: "https://game-assets.swgoh.gg/tex.charui_slave1.png",
    description:
      "Deadly Bounty Hunter Attacker that inflicts and exploits Target Lock for high area-of-effect damage",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Attacker", "Bounty Hunter", "Cargo Ship", "Scoundrel"],
    ability_classes: [
      "Ability Block",
      "AoE",
      "Counter",
      "Dispel",
      "Gain Turn Meter",
      "Reset Cooldown",
      "Taunt",
    ],
    role: "Attacker",
    capital_ship: false,
    activate_shard_count: 80,
  },
  {
    name: "Sun Fac's Geonosian Starfighter",
    id: "GEONOSIANSTARFIGHTER1",
    aliases: ["geo ship", "sunfac"],
    url: "http://swgoh.gg/ships/sun-facs-geonosian-starfighter/",
    image:
      "https://game-assets.swgoh.gg/tex.charui_geonosis_fighter_sunfac.png",
    description:
      "Punishing Separatist Tank that automatically Taunts against buffed enemies",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Geonosian", "Separatist", "Tank"],
    ability_classes: ["Gain Turn Meter", "Remove Turn Meter", "Stun", "Taunt"],
    role: "Tank",
    capital_ship: false,
    activate_shard_count: 25,
  },
  {
    name: "TIE Advanced x1",
    id: "TIEADVANCED",
    aliases: ["vader", "vader's ship", "empire tie"],
    url: "http://swgoh.gg/ships/tie-advanced-x1/",
    image: "https://game-assets.swgoh.gg/tex.charui_tieadvanced.png",
    description:
      "Fearsome Empire Attacker that shuts enemies down with stacking debuffs and permanent Target Locks",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Attacker", "Empire", "Sith"],
    ability_classes: ["AoE", "DoT", "Gain Turn Meter", "Offense Down"],
    role: "Attacker",
    capital_ship: false,
    activate_shard_count: 80,
  },
  {
    name: "TIE Reaper",
    id: "TIEREAPER",
    aliases: [
      "DEATHTROOPER",
      "death trooper",
      "shoretrooper",
      "shore trooper",
      "empire tie",
    ],
    url: "http://swgoh.gg/ships/tie-reaper/",
    image: "https://game-assets.swgoh.gg/tex.charui_tiereaper.png",
    description:
      "Defensive Empire Support that Dispels, delays cooldowns, and removes Turn Meter from the enemy Capital Ship",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Empire", "Support"],
    ability_classes: [
      "AoE",
      "Defense Down",
      "Gain Turn Meter",
      "Offense Down",
      "Remove Turn Meter",
    ],
    role: "Support",
    capital_ship: false,
    activate_shard_count: 50,
  },
  {
    name: "TIE Silencer",
    id: "TIESILENCER",
    alias: [
      "kru",
      "kylo",
      "first order tie",
      "fo tie",
      "fo silencer",
      "first order silencer",
    ],
    url: "http://swgoh.gg/ships/tie-silencer/",
    image: "https://game-assets.swgoh.gg/tex.charui_tie_silencer.png",
    description:
      "Superior First Order Attacker that gains unlimited speed and deals massive damage",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Attacker", "First Order"],
    ability_classes: [
      "Advantage",
      "Dispel",
      "Foresight",
      "Gain Turn Meter",
      "Reduce Cooldowns",
      "Stun",
    ],
    role: "Attacker",
    capital_ship: false,
    activate_shard_count: 10,
  },
  {
    name: "TIE/IN Interceptor Prototype",
    id: "TIEINTERCEPTOR",
    aliases: ["SECONDSISTER", "2nd sister", "2sister", "empire tie"],
    url: "http://swgoh.gg/ships/tiein-interceptor-prototype/",
    image:
      "https://game-assets.swgoh.gg/tex.charui_tie_interceptor_prototype.png",
    description:
      "Imperial fast-attack craft that is as nimble as it is deadly. Second Sister's force powers allow her to perform maneuvers many would consider unnatural.",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Attacker", "Empire", "Inquisitorius"],
    ability_classes: [
      "AoE",
      "Buff Immunity",
      "Dispel",
      "Foresight",
      "Gain Turn Meter",
    ],
    role: "Attacker",
    capital_ship: false,
    activate_shard_count: 145,
  },
  {
    name: "Umbaran Starfighter",
    id: "UMBARANSTARFIGHTER",
    aliases: ["fives", "clone ship"],
    url: "http://swgoh.gg/ships/umbaran-starfighter/",
    image: "https://game-assets.swgoh.gg/tex.charui_umbaran_star_fighter.png",
    description:
      "Risky Clone Tank that inflicts great damage and debuffs, but grants Turn Meter to enemies",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Clone Trooper", "Galactic Republic", "Tank"],
    ability_classes: [
      "AoE",
      "Counter",
      "Defense Down",
      "Dispel",
      "Gain Turn Meter",
      "Offense Down",
      "Remove Turn Meter",
    ],
    role: "Tank",
    capital_ship: false,
    activate_shard_count: 25,
  },
  {
    name: "Vulture Droid",
    id: "VULTUREDROID",
    aliases: ["crewless"],
    url: "http://swgoh.gg/ships/vulture-droid/",
    image: "https://game-assets.swgoh.gg/tex.charui_vulturedroid.png",
    description:
      "Persistent Separatist Attacker that inflicts Buzz Droids and is replaced when defeated",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Attacker", "Droid", "Separatist"],
    ability_classes: [
      "Ability Block",
      "AoE",
      "Assist",
      "Buff Immunity",
      "Dispel",
      "Reset Cooldown",
    ],
    role: "Attacker",
    capital_ship: false,
    activate_shard_count: 25,
  },
  {
    name: "Wedge Antilles's X-wing",
    id: "XWINGRED2",
    aliases: ["xwing", "x wing", "rebel xwing", "rebel x wing"],
    url: "http://swgoh.gg/ships/wedge-antilless-x-wing/",
    image: "https://game-assets.swgoh.gg/tex.charui_xwing_red2.png",
    description:
      "Aggressive Rebel Attacker that overwhelms enemies with debuffs",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Attacker", "Rebel"],
    ability_classes: [
      "Buff Immunity",
      "DoT",
      "Gain Turn Meter",
      "Healing Immunity",
    ],
    role: "Attacker",
    capital_ship: false,
    activate_shard_count: 25,
  },
  {
    name: "Xanadu Blood",
    id: "XANADUBLOOD",
    aliases: ["cad bane", "xb"],
    url: "http://swgoh.gg/ships/xanadu-blood/",
    image: "https://game-assets.swgoh.gg/tex.charui_xanadublood.png",
    description:
      "Debilitating Bounty Hunter Support that shuts down enemy offenses",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Bounty Hunter", "Scoundrel", "Support"],
    ability_classes: [
      "AoE",
      "Assist",
      "Bonus Attack",
      "Counter",
      "Defense Down",
    ],
    role: "Support",
    capital_ship: false,
    activate_shard_count: 25,
  },
  {
    name: "MG-100 StarFortress SF-17",
    id: "MG100STARFORTRESSSF17",
    aliases: ["rose", "reistance trooper"],
    url: "http://swgoh.gg/ships/mg-100-starfortress-sf-17/",
    image: "https://game-assets.swgoh.gg/tex.charui_mg100.png",
    description:
      "Resilient Resistance Tank that can take punishment and debilitate enemies",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Resistance", "Tank"],
    ability_classes: [
      "AoE",
      "Counter",
      "Dispel",
      "Foresight",
      "Taunt",
      "Tenacity Up",
    ],
    role: "Tank",
    capital_ship: false,
    activate_shard_count: 25,
  },
  {
    name: "TIE Echelon",
    id: "FIRSTORDERTIEECHELON",
    aliases: [
      "fo echelon",
      "first order echelon",
      "FIRSTORDEROFFICERMALE",
      "fo officer",
      "foo",
    ],
    url: "http://swgoh.gg/ships/tie-echelon/",
    image: "https://game-assets.swgoh.gg/tex.charui_firstordertieechelon.png",
    description:
      "First Order Tank that covers its allies by providing them with Stealth",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["First Order", "Tank"],
    ability_classes: [
      "Advantage",
      "Assist",
      "Counter",
      "Protection Up",
      "Stealth",
      "Taunt",
    ],
    role: "Tank",
    capital_ship: false,
    activate_shard_count: 25,
  },
  {
    name: "Outrider",
    id: "OUTRIDER",
    alieases: ["or", "dash"],
    url: "http://swgoh.gg/ships/outrider/",
    image: "https://game-assets.swgoh.gg/tex.charui_outrider.png",
    description:
      "A daring Rebel Support that increases the Download of allied ships",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Cargo Ship", "Rebel", "Scoundrel", "Smuggler", "Support"],
    ability_classes: [
      "AoE",
      "Counter",
      "Defense Down",
      "Dispel",
      "Gain Turn Meter",
      "Remove Turn Meter",
      "Stealth",
      "Taunt",
    ],
    role: "Support",
    capital_ship: false,
    activate_shard_count: 80,
  },
  {
    name: "Raven's Claw",
    id: "RAVENSCLAW",
    aliases: ["kk", "kyle katarn"],
    url: "http://swgoh.gg/ships/ravens-claw/",
    image: "https://game-assets.swgoh.gg/tex.charui_ravensclaw.png",
    description:
      "A Rebel ship crewed by Kyle Katarn that is able to dictate the flow of battle",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Jedi", "Rebel", "Support"],
    ability_classes: [
      "AoE",
      "Assist",
      "Bonus Attack",
      "Daze",
      "Defense Down",
      "Defense Up",
      "Dispel",
      "Foresight",
      "Remove Turn Meter",
      "Stealth",
      "Vulnerable",
    ],
    role: "Support",
    capital_ship: false,
    activate_shard_count: 80,
  },
  {
    name: "Profundity",
    id: "CAPITALPROFUNDITY",
    aliases: ["raddus", "admiral raddus"],
    url: "http://swgoh.gg/ships/profundity/",
    image: "https://game-assets.swgoh.gg/tex.charui_profundity.png",
    description:
      "Rebel Capital Ship that uses tactical synergy to acquire stolen plans",
    combat_type: 2,
    alignment: "Light Side",
    categories: ["Capital Ship", "Rebel"],
    ability_classes: [
      "Ability Block",
      "Advantage",
      "AoE",
      "Assist",
      "Breach",
      "Buff Immunity",
      "Counter",
      "Damage Immunity",
      "Daze",
      "Dispel",
      "Offense Up",
      "Protection Up",
      "Speed Down",
      "Stealth",
      "Stun",
      "Taunt",
      "Tenacity Down",
      "Tenacity Up",
      "Vulnerable",
    ],
    role: "Capital Ship",
    capital_ship: true,
    activate_shard_count: 80,
  },
  {
    name: "Scythe",
    id: "SCYTHE",
    url: "http://swgoh.gg/ships/scythe/",
    image: "https://game-assets.swgoh.gg/tex.charui_scythe.png",
    description:
      "Support shuttle that boosts Empire ships by providing potent buffs and summoning TIE fighters",
    combat_type: 2,
    alignment: "Dark Side",
    categories: ["Empire", "Inquisitorius", "Support", "Unaligned Force User"],
    ability_classes: [
      "AoE",
      "Defense Down",
      "Dispel",
      "Foresight",
      "Gain Turn Meter",
      "Remove Turn Meter",
      "Speed Down",
    ],
    role: "Support",
    capital_ship: false,
    activate_shard_count: 330,
  },
];

const shipsStats = [
  {
    name: "Chimaera",
    baseSpeed: 98,
    baseHealth: 0,
    baseProtection: 0,
    baseDamage: 2126,
    baseCrit: 0.2446,
    baseSpecialDamage: 3645,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00299401,
    health: 0,
    protection: 0,
    physicalDamage: 0.206859,
    critRating: 0,
    specialDamage: 1.0587915,
    specialCritRating: 0,
    potency: 0.00002268,
    tenacity: 0.00002268,
  },
  {
    name: "Endurance",
    baseSpeed: 96,
    baseHealth: 0,
    baseProtection: 0,
    baseDamage: 1531,
    baseCrit: 0.2446,
    baseSpecialDamage: 3105,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00319857,
    health: 0,
    protection: 0,
    physicalDamage: 0.35560572,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002351,
    tenacity: 0.00002351,
  },
  {
    name: "Executor",
    baseSpeed: 118,
    baseHealth: 0,
    baseProtection: 0,
    baseDamage: 2126,
    baseCrit: 0.2446,
    baseSpecialDamage: 2085,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00322083,
    health: 0,
    protection: 0,
    physicalDamage: 0.35724006,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002268,
    tenacity: 0.00002268,
  },
  {
    name: "Executrix",
    baseSpeed: 111,
    baseHealth: 0,
    baseProtection: 0,
    baseDamage: 2126,
    baseCrit: 0.2446,
    baseSpecialDamage: 2085,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00329264,
    health: 0,
    protection: 0,
    physicalDamage: 0.34295046,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002268,
    tenacity: 0.00002268,
  },
  {
    name: "Finalizer",
    baseSpeed: 110,
    baseHealth: 0,
    baseProtection: 0,
    baseDamage: 2126,
    baseCrit: 0.3529,
    baseSpecialDamage: 2085,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00299401,
    health: 0,
    protection: 0,
    physicalDamage: 0.41099618,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002267,
    tenacity: 0.00002267,
  },
  {
    name: "Home One",
    baseSpeed: 117,
    baseHealth: 0,
    baseProtection: 0,
    baseDamage: 2126,
    baseCrit: 0.2446,
    baseSpecialDamage: 3645,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00333968,
    health: 0,
    protection: 0,
    physicalDamage: 0.21449234,
    critRating: 0,
    specialDamage: 1.09786213,
    specialCritRating: 0,
    potency: 0.00002351,
    tenacity: 0.00002351,
  },
  {
    name: "Malevolence",
    baseSpeed: 113,
    baseHealth: 0,
    baseProtection: 0,
    baseDamage: 2126,
    baseCrit: 0.2446,
    baseSpecialDamage: 2085,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00299401,
    health: 0,
    protection: 0,
    physicalDamage: 0.34295046,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002268,
    tenacity: 0.00002268,
  },
  {
    name: "Negotiator",
    baseSpeed: 118,
    baseHealth: 0,
    baseProtection: 0,
    baseDamage: 2126,
    baseCrit: 0.2446,
    baseSpecialDamage: 2085,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00322083,
    health: 0,
    protection: 0,
    physicalDamage: 0.35724006,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002268,
    tenacity: 0.00002268,
  },
  {
    name: "Raddus",
    baseSpeed: 117,
    baseHealth: 0,
    baseProtection: 0,
    baseDamage: 2126,
    baseCrit: 0.2446,
    baseSpecialDamage: 3645,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00329264,
    health: 0,
    protection: 0,
    physicalDamage: 0.34295046,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002268,
    tenacity: 0.00002268,
  },
  {
    name: "Ahsoka Tano's Jedi Starfighter",
    baseSpeed: 125,
    baseHealth: 14544,
    baseProtection: 0,
    baseDamage: 2275,
    baseCrit: 0.37079999999999996,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00343375,
    health: 4.04834897,
    protection: 1.34944965,
    physicalDamage: 0.48679413,
    critRating: 0.00281286,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002351,
    tenacity: 0.00002351,
  },
  {
    name: "Anakin's Eta-2 Starfighter",
    baseSpeed: 124,
    baseHealth: 14544,
    baseProtection: 0,
    baseDamage: 2275,
    baseCrit: 0.37079999999999996,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00305745,
    health: 4.04834897,
    protection: 1.34944965,
    physicalDamage: 0.48679413,
    critRating: 0.00281286,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002351,
    tenacity: 0.00002351,
  },
  {
    name: "B-28 Extinction-class Bomber",
    baseSpeed: 101,
    baseHealth: 19440,
    baseProtection: 0,
    baseDamage: 1894,
    baseCrit: 0.32539999999999997,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.0026862,
    health: 3.73626373,
    protection: 3.73626373,
    physicalDamage: 0.38461538,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002442,
    tenacity: 0.00002442,
  },
  {
    name: "Biggs Darklighter's X-wing",
    baseSpeed: 114,
    baseHealth: 19440,
    baseProtection: 0,
    baseDamage: 1894,
    baseCrit: 0.32539999999999997,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00346764,
    health: 3.73626373,
    protection: 3.73626373,
    physicalDamage: 0.38461538,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002442,
    tenacity: 0.00002442,
  },
  {
    name: "Bistan's U-wing",
    baseSpeed: 94,
    baseHealth: 15642,
    baseProtection: 0,
    baseDamage: 2126,
    baseCrit: 0.3529,
    baseSpecialDamage: 2085,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00160538,
    health: 1.84595478,
    protection: 1.23063652,
    physicalDamage: 0.21708658,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00001198,
    tenacity: 0.00001198,
  },
  {
    name: "Cassian's U-wing",
    baseSpeed: 86,
    baseHealth: 15642,
    baseProtection: 0,
    baseDamage: 2126,
    baseCrit: 0.2446,
    baseSpecialDamage: 3645,
    baseSpecialCrit: 0.09999999999999998,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00099127,
    health: 1.1932531,
    protection: 0.79550206,
    physicalDamage: 0.07062868,
    critRating: 0,
    specialDamage: 0.32154639,
    specialCritRating: 0.00743459,
    potency: 0.00000774,
    tenacity: 0.00000774,
  },
  {
    name: "Clone Sergeant's ARC-170",
    baseSpeed: 89,
    baseHealth: 29250,
    baseProtection: 0,
    baseDamage: 2275,
    baseCrit: 0.2346,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00327228,
    health: 3.77267399,
    protection: 4.52720879,
    physicalDamage: 0.28566544,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002442,
    tenacity: 0.00002442,
  },
  {
    name: "Ebon Hawk",
    baseSpeed: 117,
    baseHealth: 27342,
    baseProtection: 0,
    baseDamage: 2126,
    baseCrit: 0.2446,
    baseSpecialDamage: 2085,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00150103,
    health: 1.76244414,
    protection: 1.17496276,
    physicalDamage: 0.17458173,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00001154,
    tenacity: 0.00001154,
  },
  {
    name: "Emperor's Shuttle",
    baseSpeed: 113,
    baseHealth: 15642,
    baseProtection: 0,
    baseDamage: 2126,
    baseCrit: 0.2446,
    baseSpecialDamage: 3645,
    baseSpecialCrit: 0.09999999999999998,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00143465,
    health: 2.11189585,
    protection: 1.40793057,
    physicalDamage: 0.10724617,
    critRating: 0,
    specialDamage: 0.48825231,
    specialCritRating: 0.01128907,
    potency: 0.00001175,
    tenacity: 0.00001175,
  },
  {
    name: "First Order SF TIE Fighter",
    baseSpeed: 134,
    baseHealth: 24354,
    baseProtection: 0,
    baseDamage: 1894,
    baseCrit: 0.28,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00336996,
    health: 4.25807692,
    protection: 1.41935897,
    physicalDamage: 0.38461538,
    critRating: 0.0058608,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002442,
    tenacity: 0.00002442,
  },
  {
    name: "First Order TIE Fighter",
    baseSpeed: 131,
    baseHealth: 14544,
    baseProtection: 0,
    baseDamage: 2275,
    baseCrit: 0.37079999999999996,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00361416,
    health: 4.20346153,
    protection: 1.40115384,
    physicalDamage: 0.50544566,
    critRating: 0.00292063,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002442,
    tenacity: 0.00002442,
  },
  {
    name: "Gauntlet Starfighter",
    baseSpeed: 100,
    baseHealth: 27342,
    baseProtection: 0,
    baseDamage: 2126,
    baseCrit: 0.2446,
    baseSpecialDamage: 2085,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00158142,
    health: 1.82870287,
    protection: 1.21913524,
    physicalDamage: 0.18114509,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00001198,
    tenacity: 0.00001198,
  },
  {
    name: "Geonosian Soldier's Starfighter",
    baseSpeed: 87,
    baseHealth: 24354,
    baseProtection: 0,
    baseDamage: 1894,
    baseCrit: 0.28,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00322344,
    health: 4.25807692,
    protection: 1.41935897,
    physicalDamage: 0.38461538,
    critRating: 0.0058608,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002442,
    tenacity: 0.00002442,
  },
  {
    name: "Geonosian Spy's Starfighter",
    baseSpeed: 89,
    baseHealth: 14544,
    baseProtection: 0,
    baseDamage: 2275,
    baseCrit: 0.2346,
    baseSpecialDamage: 3900,
    baseSpecialCrit: 0.10000000000000003,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00322344,
    health: 4.20346153,
    protection: 1.40115384,
    physicalDamage: 0.28566544,
    critRating: 0,
    specialDamage: 1.12229548,
    specialCritRating: 0.04688644,
    potency: 0.00002442,
    tenacity: 0.00002442,
  },
  {
    name: "Ghost",
    baseSpeed: 108,
    baseHealth: 14544,
    baseProtection: 0,
    baseDamage: 2275,
    baseCrit: 0.37079999999999996,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00104771,
    health: 1.34944965,
    protection: 0.44981655,
    physicalDamage: 0.16226471,
    critRating: 0.00093762,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00000783,
    tenacity: 0.00000783,
  },
  {
    name: "Han's Millennium Falcon",
    baseSpeed: 134,
    baseHealth: 24354,
    baseProtection: 0,
    baseDamage: 1894,
    baseCrit: 0.28,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00140866,
    health: 2.21466018,
    protection: 1.14088555,
    physicalDamage: 0.18185597,
    critRating: 0.00277113,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00001154,
    tenacity: 0.00001154,
  },
  {
    name: "Hound's Tooth",
    baseSpeed: 91,
    baseHealth: 29250,
    baseProtection: 0,
    baseDamage: 2275,
    baseCrit: 0.2346,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00267209,
    health: 3.38373086,
    protection: 4.06047703,
    physicalDamage: 0.25621481,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.0000219,
    tenacity: 0.0000219,
  },
  {
    name: "IG-2000",
    baseSpeed: 125,
    baseHealth: 14544,
    baseProtection: 0,
    baseDamage: 2275,
    baseCrit: 0.3708,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00303937,
    health: 3.90427667,
    protection: 1.30142555,
    physicalDamage: 0.46947015,
    critRating: 0.00271275,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002268,
    tenacity: 0.00002268,
  },
  {
    name: "Imperial TIE Fighter",
    baseSpeed: 133,
    baseHealth: 14544,
    baseProtection: 0,
    baseDamage: 2275,
    baseCrit: 0.37079999999999996,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00361416,
    health: 4.20346153,
    protection: 0,
    physicalDamage: 0.50544566,
    critRating: 0.00292063,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002442,
    tenacity: 0.00002442,
  },
  {
    name: "Jedi Consular's Starfighter",
    baseSpeed: 101,
    baseHealth: 15642,
    baseProtection: 0,
    baseDamage: 2126,
    baseCrit: 0.2446,
    baseSpecialDamage: 3645,
    baseSpecialCrit: 0.09999999999999998,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00336996,
    health: 3.76263736,
    protection: 2.5084249,
    physicalDamage: 0.22271062,
    critRating: 0,
    specialDamage: 1.01391941,
    specialCritRating: 0.02344322,
    potency: 0.00002442,
    tenacity: 0.00002442,
  },
  {
    name: "Kylo Ren's Command Shuttle",
    baseSpeed: 86,
    baseHealth: 27342,
    baseProtection: 0,
    baseDamage: 2126,
    baseCrit: 0.2446,
    baseSpecialDamage: 2085,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00095247,
    health: 1.21154395,
    protection: 0.80769597,
    physicalDamage: 0.12001142,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00000793,
    tenacity: 0.00000793,
  },
  {
    name: "Lando's Millennium Falcon",
    baseSpeed: 130,
    baseHealth: 14544,
    baseProtection: 0,
    baseDamage: 2275,
    baseCrit: 0.37079999999999996,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00171687,
    health: 2.02417448,
    protection: 0.67472482,
    physicalDamage: 0.24339706,
    critRating: 0.00140643,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00001175,
    tenacity: 0.00001175,
  },
  {
    name: "Phantom II",
    baseSpeed: 114,
    baseHealth: 14544,
    baseProtection: 0,
    baseDamage: 2275,
    baseCrit: 0.37079999999999996,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00111322,
    health: 1.34944965,
    protection: 0.44981655,
    physicalDamage: 0.16226471,
    critRating: 0.00093762,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00000783,
    tenacity: 0.00000783,
  },
  {
    name: "Plo Koon's Jedi Starfighter",
    baseSpeed: 123,
    baseHealth: 15642,
    baseProtection: 0,
    baseDamage: 2126,
    baseCrit: 0.3529,
    baseSpecialDamage: 2085,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00338672,
    health: 3.62379171,
    protection: 2.41586114,
    physicalDamage: 0.42616242,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002351,
    tenacity: 0.00002351,
  },
  {
    name: "Poe Dameron's X-wing",
    baseSpeed: 135,
    baseHealth: 15300,
    baseProtection: 0,
    baseDamage: 2179,
    baseCrit: 0.35919999999999996,
    baseSpecialDamage: 2040,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00352783,
    health: 4.04834897,
    protection: 1.34944965,
    physicalDamage: 0.48679413,
    critRating: 0.00281286,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002351,
    tenacity: 0.00002351,
  },
  {
    name: "Razor Crest",
    baseSpeed: 110,
    baseHealth: 15642,
    baseProtection: 0,
    baseDamage: 2126,
    baseCrit: 0.3529,
    baseSpecialDamage: 2085,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00343375,
    health: 4.04834897,
    protection: 1.34944965,
    physicalDamage: 0.48679413,
    critRating: 0.00281286,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002351,
    tenacity: 0.00002351,
  },
  {
    name: "Resistance X-wing",
    baseSpeed: 104,
    baseHealth: 15642,
    baseProtection: 0,
    baseDamage: 2126,
    baseCrit: 0.3529,
    baseSpecialDamage: 2085,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00336996,
    health: 3.76263736,
    protection: 2.5084249,
    physicalDamage: 0.44249084,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002442,
    tenacity: 0.00002442,
  },
  {
    name: "Rex's ARC-170",
    baseSpeed: 108,
    baseHealth: 19440,
    baseProtection: 0,
    baseDamage: 1894,
    baseCrit: 0.32539999999999997,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00329264,
    health: 3.5983913,
    protection: 3.5983913,
    physicalDamage: 0.37042263,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002351,
    tenacity: 0.00002351,
  },
  {
    name: "Rey's Millennium Falcon",
    baseSpeed: 100,
    baseHealth: 14544,
    baseProtection: 0,
    baseDamage: 2275,
    baseCrit: 0.37079999999999996,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00159928,
    health: 2.02417448,
    protection: 0.67472482,
    physicalDamage: 0.24339706,
    critRating: 0.00140643,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00001175,
    tenacity: 0.00001175,
  },
  {
    name: "Scimitar",
    baseSpeed: 94,
    baseHealth: 14886,
    baseProtection: 0,
    baseDamage: 2221,
    baseCrit: 0.3642,
    baseSpecialDamage: 1984,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00315153,
    health: 3.62379171,
    protection: 2.41586114,
    physicalDamage: 0.42616242,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002351,
    tenacity: 0.00002351,
  },
  {
    name: "Sith Fighter",
    baseSpeed: 112,
    baseHealth: 14544,
    baseProtection: 0,
    baseDamage: 2275,
    baseCrit: 0.37079999999999996,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00322344,
    health: 4.20346153,
    protection: 1.40115384,
    physicalDamage: 0.50544566,
    critRating: 0.00292063,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002442,
    tenacity: 0.00002442,
  },
  {
    name: "Slave I",
    baseSpeed: 95,
    baseHealth: 24354,
    baseProtection: 0,
    baseDamage: 1894,
    baseCrit: 0.28,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00319857,
    health: 3.95500476,
    protection: 1.31833492,
    physicalDamage: 0.35724006,
    critRating: 0.00544365,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002268,
    tenacity: 0.00002268,
  },
  {
    name: "Sun Fac's Geonosian Starfighter",
    baseSpeed: 86,
    baseHealth: 29250,
    baseProtection: 0,
    baseDamage: 2275,
    baseCrit: 0.2346,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00310449,
    health: 3.63345798,
    protection: 3.63345798,
    physicalDamage: 0.27512406,
    critRating: 0.01516,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002351,
    tenacity: 0.00002351,
  },
  {
    name: "TIE Advanced x1",
    baseSpeed: 115,
    baseHealth: 44544,
    baseProtection: 0,
    baseDamage: 2275,
    baseCrit: 0.37079999999999996,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00333968,
    health: 3.90427667,
    protection: 1.30142555,
    physicalDamage: 0.46947015,
    critRating: 0.00271275,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002268,
    tenacity: 0.00002268,
  },
  {
    name: "TIE Reaper",
    baseSpeed: 102,
    baseHealth: 15642,
    baseProtection: 0,
    baseDamage: 2126,
    baseCrit: 0.3529,
    baseSpecialDamage: 2085,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00162934,
    health: 1.84595478,
    protection: 1.23063652,
    physicalDamage: 0.21708658,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00001198,
    tenacity: 0.00001198,
  },
  {
    name: "TIE Silencer",
    baseSpeed: 137,
    baseHealth: 24354,
    baseProtection: 0,
    baseDamage: 1894,
    baseCrit: 0.28,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00308473,
    health: 3.95500476,
    protection: 1.31833492,
    physicalDamage: 0.35724006,
    critRating: 0.00544365,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002268,
    tenacity: 0.00002268,
  },
  {
    name: "Umbaran Starfighter",
    baseSpeed: 127,
    baseHealth: 29250,
    baseProtection: 0,
    baseDamage: 2275,
    baseCrit: 0.2346,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00343375,
    health: 3.63345798,
    protection: 3.63345798,
    physicalDamage: 0.27512406,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002351,
    tenacity: 0.00002351,
  },
  {
    name: "Wedge Antilles's X-wing",
    baseSpeed: 112,
    baseHealth: 14544,
    baseProtection: 0,
    baseDamage: 2275,
    baseCrit: 0.37079999999999996,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00333968,
    health: 4.04834897,
    protection: 1.34944965,
    physicalDamage: 0.48679413,
    critRating: 0.00281286,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002351,
    tenacity: 0.00002351,
  },
  {
    name: "Xanadu Blood",
    baseSpeed: 120,
    baseHealth: 15642,
    baseProtection: 0,
    baseDamage: 2126,
    baseCrit: 0.3529,
    baseSpecialDamage: 2085,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00296338,
    health: 3.62379171,
    protection: 2.41586114,
    physicalDamage: 0.42616242,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002351,
    tenacity: 0.00002351,
  },
  {
    name: "TIE Echelon",
    baseSpeed: 100,
    baseHealth: 27558,
    baseProtection: 0,
    baseDamage: 2143,
    baseCrit: 0.25,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00310449,
    health: 2.31672899,
    protection: 2.53023851,
    physicalDamage: 0.25621481,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.0000219,
    tenacity: 0.0000219,
  },
  {
    name: "TIE/IN Interceptor Prototype",
    baseSpeed: 139,
    baseHealth: 14544,
    baseProtection: 0,
    baseDamage: 2275,
    baseCrit: 0.37079999999999996,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00343375,
    health: 4.04834897,
    protection: 0,
    physicalDamage: 0.48679413,
    critRating: 0.00281286,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002351,
    tenacity: 0.00002351,
  },
  {
    name: "MG-100 StarFortress SF-17",
    baseSpeed: 90,
    baseHealth: 27558,
    baseProtection: 0,
    baseDamage: 2143,
    baseCrit: 0.25,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00149928,
    health: 1.52904113,
    protection: 1.14088555,
    physicalDamage: 0.17458173,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.0000219,
    tenacity: 0.0000219,
  },
  {
    name: "Outrider",
    baseSpeed: 129,
    baseHealth: 16560,
    baseProtection: 0,
    baseDamage: 1982,
    baseCrit: 0.25,
    baseSpecialDamage: 2040,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00338672,
    health: 3.62379171,
    protection: 2.41586114,
    physicalDamage: 0.42616242,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002351,
    tenacity: 0.00002351,
  },
  {
    name: "Raven's Claw",
    baseSpeed: 100,
    baseHealth: 26334,
    baseProtection: 0,
    baseDamage: 2048,
    baseCrit: 0.2571,
    baseSpecialDamage: 2040,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00338672,
    health: 1.12379171,
    protection: 2.41586114,
    physicalDamage: 0.22271062,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00002351,
    tenacity: 0.00002351,
  },
  {
    name: "BTL-B Y-wing Starfighter",
    baseSpeed: 174,
    baseHealth: 88213,
    baseProtection: 70755,
    baseDamage: 6739,
    baseCrit: 0.2346,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0.3816,
    baseTenacity: 0.5316,
  },
  {
    name: "Hyena Bomber",
    baseSpeed: 161,
    baseHealth: 100411,
    baseProtection: 92590,
    baseDamage: 6739,
    baseCrit: 0.2346,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0.3816,
    baseTenacity: 0.5316,
  },
  {
    name: "Imperial TIE Bomber",
    baseSpeed: 154,
    baseHealth: 108298,
    baseProtection: 88181,
    baseDamage: 6937,
    baseCrit: 0.25,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0.4097,
    baseTenacity: 0.5597,
  },
  {
    name: "Rebel Y-wing",
    baseSpeed: 174,
    baseHealth: 88213,
    baseProtection: 70755,
    baseDamage: 6739,
    baseCrit: 0.2346,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0.3816,
    baseTenacity: 0.5316,
  },
  {
    name: "Vulture Droid",
    baseSpeed: 177,
    baseHealth: 85088,
    baseProtection: 23514,
    baseDamage: 10757,
    baseCrit: 0.3912,
    baseSpecialDamage: 1939,
    baseSpecialCrit: 0.1,
    basePotency: 0.4097,
    baseTenacity: 0.5597,
  },
  {
    name: "Profundity",
    baseSpeed: 118,
    baseHealth: 0,
    baseProtection: 0,
    baseDamage: 2126,
    baseCrit: 0.2446,
    baseSpecialDamage: 3645,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00322083,
    health: 0,
    protection: 0,
    physicalDamage: 0.206859,
    critRating: 0,
    specialDamage: 1.0587915,
    specialCritRating: 0,
    potency: 0.00002268,
    tenacity: 0.00002268,
  },
  {
    name: "Scythe",
    baseSpeed: 100,
    baseHealth: 26334,
    baseProtection: 0,
    baseDamage: 2048,
    baseCrit: 0.2571,
    baseSpecialDamage: 2040,
    baseSpecialCrit: 0.1,
    basePotency: 0,
    baseTenacity: 0.15,
    speed: 0.00095247,
    health: 1.21154395,
    protection: 0.80769597,
    physicalDamage: 0.12001142,
    critRating: 0,
    specialDamage: 0,
    specialCritRating: 0,
    potency: 0.00000793,
    tenacity: 0.00000793,
  },
];

module.exports = ships.map((x) => {
  const match = shipsStats.find((stats) => stats.name === x.name);
  if (!match) {
    console.error(`No ship stats match for ${x.name}`);
  }
  return { ...x, is_ship: true, statMultipliers: { ...match } };
});
